### ISSUE TITLE
bakta_db insall 

### ISSUE THREAD

**Issue by AhmedElsherbini** [oschwengers/bakta#103]
Hi,
Thank you for making this tool.
Using Ubunto 20.04, I have installed the tool via conda. And for database download I used 
$ bakta_db download --output /media/ahmed/CC69-620B/bakta
then it failed at this command  at the step of amrfinder_update
$ amrfinder_update --force_update --database /media/ahmed/CC69-620B/bakta/db/amrfinderplus-db' 

the output is,
Running: amrfinder_update --force_update --database /media/ahmed/CC69-620B/bakta/db/amrfinderplus-db
Looking up databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
'/media/ahmed/CC69-620B/bakta/db/amrfinderplus-db/2022-04-04.1/' already exists, overwriting what was there
Downloading AMRFinder database version 2022-04-04.1 into '/media/ahmed/CC69-620B/bakta/db/amrfinderplus-db/2022-04-04.1/'
Indexing
ln: failed to create symbolic link '/media/ahmed/CC69-620B/bakta/db/amrfinderplus-db/latest': Operation not permitted

*** ERROR ***
Command failed:
ln -s '/media/ahmed/CC69-620B/bakta/db/amrfinderplus-db/2022-04-04.1' '/media/ahmed/CC69-620B/bakta/db/amrfinderplus-db/latest'
status = 256

HOSTNAME: ?
SHELL: /bin/bash
PWD: /media/ahmed/CC69-620B/00_Ph.D/DATA_results/7_search_database
PATH: /home/ahmed/anaconda3/envs/bacta/bin:/home/ahmed/anaconda3/condabin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Progam name:  amrfinder_update
Command line: amrfinder_update --force_update --database /media/ahmed/CC69-620B/bakta/db/amrfinderplus-db

any clue?
Thanks in advance.

**Comment by oschwengers** [comment]
Hi @AhmedElsherbini , thanks for reaching out.
I just tested the latest Bakta version from a fresh Conda environment and everything worked as expected:
```
bakta_db download --output db
fetch DB versions...
	... compatible DB versions: 2
download database: v3.1, 2022-02-03, DOI: 10.5281/zenodo.5961398, URL: https://zenodo.org/record/5961398/files/db.tar.gz...
|████████████████████████████████████████| 28593946/28593946 [100%] in 50:20.0 (9468.14/s)
	... done
check MD5 sum...
	...database file OK: 95a140c0c2a40153fdc9794e89860944
extract DB tarball: file=/home/oliver/tmp/bakta-gh-103/db/db.tar.gz, output=/home/oliver/tmp/bakta-gh-103/db
successfully downloaded Bakta database!
	version: 3.1
	DOI: 10.5281/zenodo.5961398
	path: /home/oliver/tmp/bakta-gh-103/db/db
update AMRFinderPlus database...
	... done

Run Bakta using '--db /home/oliver/tmp/bakta-gh-103/db/db' or set a BAKTA_DB environment variable: 'export BAKTA_DB=/home/oliver/tmp/bakta-gh-103/db/db'
```

Could you provide some more information which Bakta and AMRFinder verison you have installed in your conda environment:
```
bakta --version
amrfinder --version
```
Could you try to manually execute the `amrfinder_update --force_update --database /media/ahmed/CC69-620B/bakta/db/amrfinderplus-db'` command and see if this runs as expected?

**Comment by AhmedElsherbini** [comment]
Thanks, Oliver for your fast response,
For bakta --version it is "bakta 1.4.0"
For amr_finder it is "3.10.24"
```python
amrfinder_update --force_update --database /media/ahmed/CC69-620B/bakta/db/amrfinderplus-db
Running: amrfinder_update --force_update --database /media/ahmed/CC69-620B/bakta/db/amrfinderplus-db
Looking up databases at https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/
'/media/ahmed/CC69-620B/bakta/db/amrfinderplus-db/2022-04-04.1/' already exists, overwriting what was there
Downloading AMRFinder database version 2022-04-04.1 into '/media/ahmed/CC69-620B/bakta/db/amrfinderplus-db/2022-04-04.1/'

*** ERROR ***
CURL: Cannot download from https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/3.10/2022-04-04.1/AMR.LIB

HOSTNAME: ?
SHELL: /bin/bash
PWD: /home/ahmed
PATH: /home/ahmed/anaconda3/envs/bacta/bin:/home/ahmed/anaconda3/condabin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Progam name:  amrfinder_update
Command line: amrfinder_update --force_update --database /media/ahmed/CC69-620B/bakta/db/amrfinderplus-db


```

**Comment by oschwengers** [comment]
No problem. I'm glad that it's working now :D
