### ISSUE TITLE
database download

### ISSUE THREAD

**Issue by fetyj** [oschwengers/bakta#107]
Hi,
Thank you for making this great tool.
I have install bakta using conda but I got this error when trying to download database, could you help solve it?
cmd : `bakta_db download --output ./bakta_database`
`
fetch DB versions...
	... compatible DB versions: 2
download database: v3.1, 2022-02-03, DOI: 10.5281/zenodo.5961398, URL: https://zenodo.org/record/5961398/files/db.tar.gz...
|███████████████████████████████▎⚠       | (!) 22340191/28593946 [78%] in 3:32:55.8 (1748.63/s)
	... done
check MD5 sum...
Error: corrupt database file! MD5 should be '95a140c0c2a40153fdc9794e89860944' but is 'b4b607b022939c7f190955058ec132e3'`
bakta version : `bakta 1.4.0`

Thanks
Fety

**Comment by oschwengers** [comment]
Hi @fetyj,
is this reproducible? Have you tried it several times? It looks like either the download or the stored file is corrupt.

**Comment by fetyj** [comment]
Hi, 
I've tried only once then I downloaded manually but I'll give it a try and let you know if I'm getting the same error.
Fety

**Comment by fetyj** [comment]
I tried a second time then everything went just fine.
Thanks for your time :) and sorry for any bothering
Fety
