### ISSUE TITLE
Error in 'Revise special cases'

### ISSUE THREAD

**Issue by conmeehan** [oschwengers/bakta#108]
**Describe the bug**
When annotating a genome I get the following error:
       revise special cases...
Traceback (most recent call last):
  File "/home/cmeehan/miniconda3/envs/bakta/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/home/cmeehan/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/main.py", line 293, in main
    feat_cds.revise_special_cases_annotated(cdss)
  File "/home/cmeehan/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/features/cds.py", line 446, in revise_special_cases_annotated
    dnaA.pop('truncated')
KeyError: 'truncated'

Command run: bakta --db /mnt/DATA3/databases/bakta/ --verbose --output g_SRR4067881 --prefix g_SRR4067881 --locus-tag g_SRR4067881--threads 20 g_SRR4067881.fasta

It was installed via conda and works on over 12k genomes, I only get this error on 4 genomes, all from the SRA and assembled via Skesa. Hopefully can help.

Cheers,
Conor

**Comment by oschwengers** [comment]
Hi Conor, thanks for reporting! I'll have a look and check what is going on here.

**Comment by oschwengers** [comment]
Hi @conmeehan, I tested the `SRR4067881` files with both Shovill and SKESA. Bakta annotated both assemblies w/o any issues. Could provide one of these assemblies so I can reproduce this issue and debug it?

**Comment by conmeehan** [comment]
Sure, one of the ones that failed is attached. 
[g_SRR4067954.txt](https://github.com/oschwengers/bakta/files/8694513/g_SRR4067954.txt)


C

**Comment by oschwengers** [comment]
Indeed there was a tiny bug lurking that in your example "nicely" played together with two typos of a recent commit. They're both fixed and I'll provide a patch release soon.
Thanks again for reporting!

**Comment by conmeehan** [comment]
That worked! Thanks so much.
