### ISSUE TITLE
Add alignment identity and coverage value in the gff output file?

### ISSUE THREAD

**Issue by Tonny-zhou** [oschwengers/bakta#110]
**Is your feature request related to an existing issue or bug?**
Briefly reference any existing issues this is related to.

**Is your new feature related to a general problem?**
Please provide us with a concise description of what the problem is:
- what happened which was *not* expected
- what did *not* happen which was expected
- what would you like to happen or see in the output

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or information about your feature request here.

Dear author,

Thank you for this great annotation tool! I just want to ask that if it is possibile to add the specific alignment identity and coverage values for each ORF (Remaining unidentified protein sequences after AFSI process)? I think this could help me to better  judge the accuracy of ORF annotation.

**Comment by oschwengers** [comment]
Hi @Tonny-zhou ,
thanks for reaching out. You can find these values along with all information Bakta internally has in the JSON result file.

Here's an example of our GCF_000008865.2 test genome:
```
"psc": {
                "uniref90_id": "UniRef90_A0A091C4I8",
                "query_cov": 0.9805194805194806,
                "identity": 0.556,
                "valid": false,
                "product": "Allantoinase",
                "uniref50_id": "UniRef50_A0A091C4I8"
            },
```

Is this sufficient to answer your questions?
