### ISSUE TITLE
GenBank crash

### ISSUE THREAD

**Issue by Aluminio-visto** [oschwengers/bakta#111]
Hi there,
first of all, let me thank you for this absolutely amazing tool you have created.
I was running my first bakta test with a small P.putida contigs.fasta file assembled with spades, and I ran into this bug:

**bakta --db /home/usuario/miniconda3/envs/tormes-1.3.0/db/bakta/ --verbose --output bakta/ --prefix prueba --threads 30 contigs.fasta**

> Bakta v0.5
> Options and arguments:
>         input: /home/usuario/Seqs/P_putida/WGS_Pseudomonasputida_Alain_2020_02_18/spades/pMS5414_S1/contigs.fasta
>         db: /home/usuario/miniconda3/envs/tormes-1.3.0/db/bakta, version 1.1
>         output: /home/usuario/Seqs/P_putida/WGS_Pseudomonasputida_Alain_2020_02_18/spades/pMS5414_S1/bakta
>         prefix: prueba
>         tmp directory: /tmp/tmp5s_521s9
>         # threads: 30
>         translation table: 11
> parse genome sequences...
>         imported: 28
>         filtered & revised: 28
>         contigs: 28
> predict tRNAs...
>         found: 3
> predict tmRNAs...
>         found: 0
> predict rRNAs...
>         found: 4
> predict ncRNAs...
>         found: 3
> predict ncRNA regions...
>         found: 4
> predict CRISPR arrays...
>         found: 0
> predict & annotate CDSs...
>         predicted: 338 
>         discarded spurious: 3
>         detected IPSs: 290
>         found PSCs: 37
>         lookup annotations...
>         mark hypotheticals and combine annotations...
> analyze hypotheticals...
>         detected Pfam hits: 5 
>         calculated proteins statistics
> extract sORF...
>         potential: 3387
>         discarded due to overlaps: 2685
>         discarded spurious: 0
>         detected IPSs: 1
>         found PSCs: 0
>         lookup annotations...
>         filter and combine annotations...
>         filtered sORFs: 1
> detect gaps...
>         found: 0
> detect oriCs/oriVs...
>         found: 1
> detect oriTs...
>         found: 0
> apply feature overlap filters...
> select features and create locus tags...
> selected: 352
> 
> genome statistics:
>         Genome size: 372,657 bp
>         Contigs/replicons: 28
>         GC: 46.4 %
>         N50: 286,545
>         N ratio: 0.0 %
>         coding density: 86.9 %
> 
> annotation statistics:
>         tRNAs: 3
>         tmRNAs: 0
>         rRNAs: 4
>         ncRNAs: 3
>         ncRNA regions: 4
>         CRISPR arrays: 0
>         CDSs: 336, hypotheticals: 41
>         sORFs: 1
>         gaps: 0
>         oriCs/oriVs: 1
>         oriTs: 0
> 
> write JSON output...
> write TSV output...
> write GFF3 output...
> write GenBank output...
> Traceback (most recent call last):
>   File "/home/usuario/miniconda3/envs/tormes-1.3.0/bin/bakta", line 10, in <module>
>     sys.exit(main())
>   File "/home/usuario/miniconda3/envs/tormes-1.3.0/lib/python3.6/site-packages/bakta/bakta.py", line 446, in main
>     genbank.write_genbank(genome, features, genbank_path)
>   File "/home/usuario/miniconda3/envs/tormes-1.3.0/lib/python3.6/site-packages/bakta/io/genbank.py", line 208, in write_genbank
>     SeqIO.write(contig_list, fh, format='genbank')
>   File "/home/usuario/miniconda3/envs/tormes-1.3.0/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 531, in write
>     count = writer_class(handle).write_file(sequences)
>   File "/home/usuario/miniconda3/envs/tormes-1.3.0/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 235, in write_file
>     count = self.write_records(records, maxcount)
>   File "/home/usuario/miniconda3/envs/tormes-1.3.0/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 209, in write_records
>     self.write_record(record)
>   File "/home/usuario/miniconda3/envs/tormes-1.3.0/lib/python3.6/site-packages/Bio/SeqIO/InsdcIO.py", line 1005, in write_record
>     self._write_the_first_line(record)
>   File "/home/usuario/miniconda3/envs/tormes-1.3.0/lib/python3.6/site-packages/Bio/SeqIO/InsdcIO.py", line 757, in _write_the_first_line
>     raise ValueError("Need a Nucleotide or Protein alphabet")
> ValueError: Need a Nucleotide or Protein alphabet
> 

So it only returns the gff3, the json and the tsv file. I have no clue what the problem might be, as translation_table is 11 by default.
here you might find my fastas, logs, json and so on...
[crush.tar.gz](https://github.com/oschwengers/bakta/files/8814030/crush.tar.gz)

**Comment by oschwengers** [comment]
Hi @Aluminio-visto ,
thanks for reaching out and reporting. Due to the information you're using a very outdated version (`v.05`). Therefore, may I first ask you to update to the most recent release `v1.4.1` and repeat the annotation? Unfortunately, we have no capacities to maintain older versions.

**Comment by oschwengers** [comment]
Hi,
Conda is indeed our preferred installation procedure. If you've installed Bakta within an existing env using the command shown above, then there seem to be some dependency issues that forestall Conda from installing the latest Bakta version. In this case, a fresh or dedicated env might indeed help. For the database: just remove the old one since we made some substantial updated from 0.5 to 1.4.1 and thus you need db version >3.0.

**Comment by Aluminio-visto** [comment]
Hello @oschwengers, I tried to make a fresh installation on a new virtual environment and it did worked perfectly, thank you very much!!

**Comment by oschwengers** [comment]
Thanks for reporting back. Glad, it's working as expected!
