### ISSUE TITLE
Regarding AMRfinderplus database error

### ISSUE THREAD

**Issue by davidtong28** [oschwengers/bakta#114]
I manually downloaded bakta database and then **moved it to another location**. Bakta will refuse to run because it cannot detect AMRfinderplus database. Running amrfinder_update, it says however that the AMRfinderplus database is already installed. But no matter how many times I re-download it with `amrfinder_update --force_update`, bakta still cannot detect it.
I found that this is due to `<new-db-path>/amrfinderplus-db/latest` links to `<old-db-path>/amrfinderplus-db/<db_version>`. I deleted `<new-db-path>/amrfinderplus-db/latest` and ran `amrfinder_update --force_update` again. This time the link was created correctly and bakta is able to run.

**Comment by oschwengers** [comment]
Thanks pointing out. But this is rather an issue of AMRfinderplus that of Bakta. You could either manually download the database, move it to its final location and *then* call `amrfinder_update`  ... or use Bakta's internal download script via `bakta_db` which takes care of this. If this bahaviour of amrfinder is reproducible, you maybe would like to report it upstream?
