### ISSUE TITLE
Inconsistency in annotation on subsets of same sequence 

### ISSUE THREAD

**Issue by lerminin** [oschwengers/bakta#121]
Hi there, 

I've noticed that when I run bakta on subsets of the same nucleotide sequence, my output annotations are quite different. I am trying to annotate a 140 kb plasmid, and when I subset a 22 kb sequence from anywhere in the plasmid (100 % identity), the annotations and open reading frame coordinates do not match the annotations on the identical 22 kb section on the 140 kb sequence; there tends to be shorter, more hypothetical open reading frames in the 22 kb subset. I thought this might be related to the input size, but when I subset 15 kb and 80 kb from the 140 kb sequence, the coordinates are different again and the difference seems to be random. 

I would expect that the annotations would be the same on the identical nucleotide sequences, regardless of the total input length. 

Here is an example of the coordinates of the open reading frames being called for each contig when they all start from the same base position (ORFs in bold are shared across all subsets):  

| 140 kb plasmid  | 15 kb subset | 22 kb subset | 80 kb subset |
| ------------- | ------------- | ------------- | ------------- |
| **1..978**  | **1..978** | **1..978**  | **1..978** |
| 1054..1173  | 1054..1173 | 1177..1266  | **1263..2003**  |
| **1263..2003** | **1263..2003** | **1263..2003**  | **2679..3848**  |
| **2679..3848** | **2679..3848** | 2014..2124  | **4695..4967**  |
| 4064..4177 | **4695..4967** | **2679..3848**  | 5563..5928  |
| **4695..4967** | 5563..5928  | 4064..4177  | 6210..8180  |
| 5563..5928  | 6210..8180 | **4695..4967**  | 8187..8978  |
| 6210..8180 |  8187..8978 | 5414..5605  | 9041..9559  |
| 8187..8978 | 9041..9472 | 5563..5973  | 9717..10496  |
| 9041..9559 | 9717..10496 | 5970..6125  | 10496..11518  |
| 9717..10496  | 10496..11518 | 6469..6717  | 11532..12290  |

I'm running the following command with bakta v1.4.2 and database v3.1:
` bakta --db ${DB} --output ${HEADER} --prefix ${HEADER} --threads $THREADS ${GENOME}`

Am I correct in assuming that these subsets should all have identical annotations if their nucleotide sequences are 100% identical?

**Comment by lukasjelonek** [comment]
Hey @lerminin,

this might be an effect of the underlying gene predictor (`prodigal`). It trains its prediction model based on features extracted from your input sequences (the longest orfs, as I remember). The longer your data, the more of these training features are expected. 

You can try to run `prodigal` directly to check if it responsible for this behaviour: `prodigal -i <contigs> -f gff -o <ouputgff>`

You can also train `prodigal` on a sequence, save the model and use the trained model for all your subsets to (hopefully) get the same or at almost the same results.

You might also have a look at the command line generator for the prodigal prediction: https://github.com/oschwengers/bakta/blob/b5203d3efe9162f452c1d9d8864ba3f01287cca8/bakta/features/cds.py#L77

**Comment by oschwengers** [comment]
Hi @lerminin, exactly this! On short sequences (I can't remember the exact cutoff, either 20 or 50 kbp), Prodigal defaults to its generic (metagenome) model which is not as accurate as the trained models, as described above. You could either provide a pretrained model for the sorter sequences or (if this is also possible in your setup) annotate the entire plasmid an extract annotated subregions afterwards.

**Comment by lerminin** [comment]
I clearly need to read up on Prodigal! Annotating the entire plasmid and extracting the annotated subregions is good enough for my purposes. Thank you for the clarification!
