### ISSUE TITLE
Problem with DB download

### ISSUE THREAD

**Issue by diecasfranco** [oschwengers/bakta#128]
Hi all, 
I'm having this issue with database download. After several attempts, it is the same output. Also, I've tried with wget and directly from the link without success. 

Any advice?
Thanks

Bakta software version: 1.5.0
Required database schema version: 4

fetch DB versions...
	... compatible DB versions: 1
download database: v4.0, 2022-08-29, DOI: 10.5281/zenodo.7025248, URL: https://zenodo.org/record/7025248/files/db.tar.gz...
|⚠                                       | (!) 1119/31734559 [0%] in 3:31.7 (5.28/s)
	... done
check MD5 sum...
Error: corrupt database file! MD5 should be '4116192902e88140b19b5e4d88be9fa1' but is '5eddaefee4842cab7836f21c3ddc3cba'

**Comment by oschwengers** [comment]
Hi @diecasfranco , thanks for reporting!
I've tested the entire roundtrip (Bakta installation via Conda, download via bakta_db download, execution of fresh Bakta and DB) without any issues.

Indeed, Zenodo reported that they have some issues with their service - currently, only UPload issues reported, but who knows. I'd suggest to wait a while and try again later: https://twitter.com/ZENODO_ORG/status/1565307575360421889
