### ISSUE TITLE
bakta gives blank output

### ISSUE THREAD

**Issue by neelam19051** [oschwengers/bakta#129]
Hi, i am using bakta in loop for multiple genomes and it giving blank output as well as when i am providing --protein tag fasta file it says file format errors.
home/bvs/neelam/complete_genome_cp/P_aeruginosa_12939.fna.gz
parse genome sequences...
	imported: 1
	filtered & revised: 1
	contigs: 1

start annotation...
predict tRNAs...
	found: 66
predict tmRNAs...
	found: 1
predict rRNAs...
	found: 12
predict ncRNAs...
	found: 50
predict ncRNA regions...
	found: 36
predict CRISPR arrays...
	found: 1
predict & annotate CDSs...
	predicted: 6032 
	discarded spurious: 0
	revised translational exceptions: 1
	detected IPSs: 5774
	found PSCs: 223
	found PSCCs: 16
	lookup annotations...
	conduct expert systems...
		amrfinder: 17
		protein sequences: 614
**_**ERROR: User proteins file Fasta format not valid!**_**

However, input fasta file look like this-

- >tr|A0A8G7HZP4|A0A8G7HZP4_PSEAI Multidrug efflux RND transporter periplasmic adaptor subunit MexJ OS=Pseudomonas aeruginosa OX=287 GN=mexJ PE=3 SV=1
- MYRHIPLVALSLLSSLFLAACGNGTPPPAAARPAIVVQPQPAGEVSQAFPGEIRARHEPELAFRIGGKVIRRLVEVGERVKKDQPLAELDPQDVRLQLEAARAQVSAAEANLQTVRAEYRRYRTLLDRNLVSHSQFENIQNSYRAGEARLKQIRAEFNVADNQAGYAVLRSPQDGVIASRRVEVGQVVAAGQTVFSLAADGEREVLIGLPEHSFERFRIGQPVSVELWSQRNRRFAGHIRELSPAADPQSRTFAARVAFDDRATPAELGQSARVYVAAAEAVPLSVPLSALTAEAGQAFVWVVEPGSSTLRRQPVRTGPYAEDRVPVLEGLKAGDWVVATGVQVLREGQQVRPIDRANRTVKLAAKE

Thanks

**Comment by oschwengers** [comment]
Hi @neelam19051,
these empty files are caused by the error occurring due to a wrong file format. In order to use user-provided reference proteins via `--proteins`, protein sequences must be formatted in one of two possible formats, so that Bakta can extract all required information, *e.g.* gene symbol, product, dbxrefs, in a well-structured way:
```
# short:
>id gene~~~product~~~dbxrefs
MAQ...

# long:
>id min_identity~~~min_query_cov~~~min_subject_cov~~~gene~~~product~~~dbxrefs
MAQ...
```

So, for example your protein sequence above could be provided in the *short* format as:
```
>A0A8G7HZP4 mexJ~~~multidrug efflux RND transporter periplasmic adaptor subunit MexJ~~~
MYRHIPLVALSLLSSLFLAACGNGTPPPAAARPAIVVQPQPAGEVSQAFPGEIRARHEPELAFRIGGKVIRRLVEVGERVKKDQPLAELDPQDVRLQLEAARAQVSAAEANLQTVRAEYRRYRTLLDRNLVSHSQFENIQNSYRAGEARLKQIRAEFNVADNQAGYAVLRSPQDGVIASRRVEVGQVVAAGQTVFSLAADGEREVLIGLPEHSFERFRIGQPVSVELWSQRNRRFAGHIRELSPAADPQSRTFAARVAFDDRATPAELGQSARVYVAAAEAVPLSVPLSALTAEAGQAFVWVVEPGSSTLRRQPVRTGPYAEDRVPVLEGLKAGDWVVATGVQVLREGQQVRPIDRANRTVKLAAKE
```

Using the *long* format, you could also provide distinct thresholds for min sequence identity, query coverage and subject coverage. You can find more detailed information in the input/output section of the readme: https://github.com/oschwengers/bakta#input-and-output

Best regards!

**Comment by neelam19051** [comment]
Thank you so much for your time...Now it's working...Can you please share example for long along with the above example.

**Comment by oschwengers** [comment]
Sure.
Let's assume you would like to annotate protein sequences that share 75.5% sequence identity with an alignment covering 95% of the query, and 80% of the given subject protein sequence, you would simply add `75.5~~~95~~~80~~~` to the Fasta header description of the short format example:
```
>A0A8G7HZP4 75.5~~~95~~~80~~~mexJ~~~multidrug efflux RND transporter periplasmic adaptor subunit MexJ~~~
MYRHIPLVALSLLSSLFLAACGNGTPPPAAARPAIVVQPQPAGEVSQAFPGEIRARHEPELAFRIGGKVIRRLVEVGERVKKDQPLAELDPQDVRLQLEAARAQVSAAEANLQTVRAEYRRYRTLLDRNLVSHSQFENIQNSYRAGEARLKQIRAEFNVADNQAGYAVLRSPQDGVIASRRVEVGQVVAAGQTVFSLAADGEREVLIGLPEHSFERFRIGQPVSVELWSQRNRRFAGHIRELSPAADPQSRTFAARVAFDDRATPAELGQSARVYVAAAEAVPLSVPLSALTAEAGQAFVWVVEPGSSTLRRQPVRTGPYAEDRVPVLEGLKAGDWVVATGVQVLREGQQVRPIDRANRTVKLAAKE
´´´

**Comment by neelam19051** [comment]
Thanks a lot ...It was really helpful..

**Comment by oschwengers** [comment]
You're welcome!

**Comment by neelam19051** [comment]
I will definitely acknowledge you guys on my thesis.... Thank you.
