### ISSUE TITLE
INSDC compliance can fail in conjunction with `--keep-contig-headers`

### ISSUE THREAD

**Issue by St4NNi** [oschwengers/bakta#134]
**Describe the bug**
When running Bakta with `--keep-contig-headers` and `--compliant` the tool can fail when the original contig headers exceed 25 characters.

error message:
```
ERROR: INSDC compliance failed! Contig ID (LONG_CONTIG_NAME_1___NODE_1_length_1753306_cov_158.170498) larger than 25 characers
```

- Bakta version 1.5
- Databse 4.0

**Comment by oschwengers** [comment]
Thanks @St4NNi,
I'll have a look at this soon.

Best regards!

**Comment by oschwengers** [comment]
Hi, I think it might be best to stick to this behavior. Users might want to use their existing and compliant IDs. If these do not comply with INSDC requirements, it's IMHO OK for Bakta to throw this error (-> `fail fast`). Then, users can decide to: a) change their IDs, or b) run Bakta without the `--compliant` option.

I'll close this for now. If I slipped some cases, please don't hesitate to re-open it.
