### ISSUE TITLE
option to do not clean temp dir 

### ISSUE THREAD

**Issue by EricDeveaud** [oschwengers/bakta#137]
Hello

woud it be possible to have an option to not remove temporary directory and files.
this will allow one to perform some analysis psot-mortem in case of crash ;-)

regards

Eric

**Comment by oschwengers** [comment]
Hi Eric,
yes, this makes totally sense! However, I'd refuse to introduce a new option, but instead hook this new behavior onto the existing `--debug` option.

Any thoughts?

**Comment by oschwengers** [comment]
This is now active on `main` and be part of the upcoming `v1.5.1` release.
Thanks for the suggestions and best regards!
