### ISSUE TITLE
micromamba-based Dockerfile

### ISSUE THREAD

**Issue by simone-pignotti** [oschwengers/bakta#148]
Hi, not really a feature request, but I was wondering whether you considered using the micromamba [docker image](https://github.com/mamba-org/micromamba-docker) for your Dockerfile. It would probably greatly simplify its definition.
I have tested the following, and apart from `deepsig` (which I have troubles installing even in a freshly created conda environment, without listing other dependencies...), it works perfectly:
```
FROM mambaorg/micromamba:latest
RUN micromamba install -y -n base -c conda-forge -c bioconda bakta && micromamba clean --all --yes
```

**Comment by oschwengers** [comment]
Hi @simone-pignotti thanks for the heads-up!
Indeed, it looks very promising and we already had a look at it. Unfortunately, we couldn't get it to work in different Docker/Singularity/Podman and run/exec settings (#106). But, we'll keep an eye on it and see, if we can use it maybe at some later point.

Thanks again and best regards!

**Comment by simone-pignotti** [comment]
I see, thank you!
