### ISSUE TITLE
 Bakta Web _ TypeError: Failed to fetch

### ISSUE THREAD

**Issue by FaisalAlj** [oschwengers/bakta#152]
Hello,

I'm trying to use the Bakta Web Version to get the annotation of the genome, but every time i'm trying to upload the fasta file and then submit it, i get the following error "TypeError: Failed to fetch".

Anyone has an idea, why i'm getting this error ?

Thanks in advance :)

**Comment by lukasjelonek** [comment]
Hi @FaisalAlj,

we currently face an infrastructure problem that (in the bad case) will take a while to fix. I'll post a notification here when we decided how handle it.

**Comment by St4NNi** [comment]
Hi @FaisalAlj thank you for your report,
we have fixed the issue, please try again and feel free to report any additional issues that might occur.
Thanks !

**Comment by FaisalAlj** [comment]
Thanks alot @lukasjelonek and @St4NNi . Now it works perfectly fine 💯  :)
