### ISSUE TITLE
Deleting databases as local user

### ISSUE THREAD

**Issue by alanbeavan** [oschwengers/bakta#155]
Hello,

I am just starting out with bakta, which I installed using conda. I downloaded the databases using:

bakta_db download --output <output-path>

However, I no longer want the databases on the system I downloaded them to, so I tried to remove them. Using the unix command rm gives me the following error:

rm: cannot remove 'db/rRNA.i1f': Permission denied

for every file in the directory db/. I don't seem to be able to remove them without sudo access. Please advise.

Best regards,
Alan

**Comment by oschwengers** [comment]
Hi @alanbeavan,
have you downloaded the database yourself? In this case you should be able to remove it via `rm -rf db/`

**Comment by alanbeavan** [comment]
So I would have thought but no - that is exactly what I did.

I downloaded the databases using bakta_db

**Comment by oschwengers** [comment]
OK, sry, my fault. Just set the permissions and it should be possible to remove the database: `chmod 755 db`

**Comment by alanbeavan** [comment]
Thanks - I should have thought to do that. That's sorted
