### ISSUE TITLE
Deepsig not executable or installed after conda installation?

### ISSUE THREAD

**Issue by cizydorczyk** [oschwengers/bakta#156]
When attempting to annotate an *S. aureus* genome, I get the following error after installing Bakta in a conda environment:

```
(bakta-env) user@Precision-Tower:~/software/bakta-db-2022-08-29$ bakta --db ~/software/bakta-db-2022-08-29/db/ --min-contig-length 200 --prefix JMB00961a --output ~/bakta-test/ --genus Staphylococcus --species aureus --strain JMB00961a --translation-table 11 --gram + --compliant --threads 8 --debug ~/isolate-assembly.fasta 
ERROR: deepsig not found or not executable! Please make sure deepsig is installed and executable or skip requiring workflow steps via via '--gram ?'.
```

Checking the installed packages in the `bakta-env` does not find any called DeepSig (or anything related).

**Comment by apredeus** [comment]
This is still happening with the newest version (1.9.1) installed with bioconda - any fixes?

**Comment by oschwengers** [comment]
No, unfortunately, the DeepSig Conda package depends on Python 3.8 which is kind of a _software maintenance_ no go on the long term. I therefore excluded DeepSig from the Bakta Conda dependency list. If you're interested in using DeepSig within Bakta, then you need to create your own Conda environment enforcing Conda to setup Python 3.8.

**Comment by apredeus** [comment]
Thank you! I decided to skip it for now, but thank you for the info.
