### ISSUE TITLE
IndexError in predict & annotate CDSs / pseudogenes

### ISSUE THREAD

**Issue by EdgarTheOrange** [oschwengers/bakta#157]
*** **EDIT**: I've just seen that it was asked before here: https://github.com/oschwengers/bakta/issues/133, will try to update bakta ***

Hi, Thank you for the tool! it helps us a lot. 
I'm interested in running three parts of the program: CDS-, pseudogenes- and sORF- detection, against 300MB each fasta files (each has about 30k long reads). 

Most of the times it runs without a problem, but in about 20% of the times it crashes with this error:

```
predict & annotate CDSs...
        predicted: 459354
        discarded spurious: 797
        revised translational exceptions: 0
        detected IPSs: 5009
        found PSCs: 19137
        found PSCCs: 125907
        lookup annotations...
        conduct expert systems...
                amrfinder: 162
                protein sequences: 125
        combine annotations and mark hypotheticals...
        detect pseudogenes...
                pseudogene candidates: 14598
Traceback (most recent call last):
  File "/<conda_env_path>/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/<conda_env_path>/lib/python3.9/site-packages/bakta/main.py", line 286, in main
    pseudogenes = feat_cds.detect_pseudogenes(pseudo_candidates, cdss, genome) if len(pseudo_candidates) > 0 else []
  File "/<conda_env_path>/lib/python3.9/site-packages/bakta/features/cds.py", line 643, in detect_pseudogenes
    observations, positions = detect_pseudogenization_observations(
  File "/<conda_env_path>/lib/python3.9/site-packages/bakta/features/cds.py", line 798, in detect_pseudogenization_observations
    compare_alignments(observations, alignment, ref_alignment, cds, positions, elongated_edge)
  File "/<conda_env_path>/lib/python3.9/site-packages/bakta/features/cds.py", line 815, in compare_alignments
    if alignment[up_length-1] == 'M' and ref_alignment[up_length-1] != 'M':
IndexError: string index out of range
```

The command I used is:
`bakta --db <path>/Bakta/db --output <path_to_out_dir> -v --tmp-dir <path_to_tmp_dir> --skip-trna --skip-tmrna --skip-rrna --skip-ncrna --skip-ncrna-region --skip-crispr --skip-ori <path_to_fasta>`

Running the files that failed with more threads/memory resulted with the same error (4 or 8 cores, each with 32GB/40GB/64GB RAM). 

Anyone also had this problem and might have found a solution? I would appreciate any help!

**Comment by oschwengers** [comment]
HI @EdgarTheOrange,
I hope this is fixed by v1.5.1 and I close it for now.

Just in case the issue remains, please do not hesitate to re-open it.
Best regards!
