### ISSUE TITLE
AMRFinderPlus database not installed! 

### ISSUE THREAD

**Issue by dfeistel3** [oschwengers/bakta#159]
I keep getting this error:
`ERROR: AMRFinderPlus database not installed! Please, install AMRFinderPlus's internal database by executing: 'amrfinder_update --database <database-path>/amrfinderplus-db'. This must be done only once.`

I have tried to updated the amrfinderplus database, and the entire database.  I have tried to use `--db` or export $BAKTA_DB with the `realpath` but that is not working either.  

bakta was installed using condo and I'm working in a cluster

**Comment by oschwengers** [comment]
Hi, this is most certainly an AMRFinder issue related to a symlink within the AMRFinder db. It's a symlink pointing to an absolute path and this often gets broken when the database is manually copied to another directory. Therefore, I'd like to kindly refer you to https://github.com/oschwengers/bakta/issues/151

A possible solution would be to delete the entire content within the `amrfinderplus-db` directory *including* the symbolic link and then re-install the AMRFinder db via `amrfinder_update --database <database-path>/amrfinderplus-db`.

```
cd <BAKTA_DB_PATH>
rm -rf amrfinderplus-db/*
amrfinder_update --database amrfinderplus-db/
```

BTW, I also recommend to update AMRFinder to the latest version `3.10.42`

**Comment by oschwengers** [comment]
Thanks to the AMRFinder developers https://github.com/ncbi/amr/issues/101, this should not happen anymore after using release [v3.10.45](https://github.com/ncbi/amr/releases/tag/amrfinder_v3.10.45)

**Comment by oschwengers** [comment]
I hope the information above and within #151  helped to solve this issue. I'll close this issue for now. Just in case, please do not hesitate to re-open it if it remains.
