### ISSUE TITLE
Not recognizing fsa.gz file or fsa file or fasta file

### ISSUE THREAD

**Issue by KFWins2022** [oschwengers/bakta#167]
Hey!

I am having a significant challenge with getting this to run but it likely is due to user error.

I inputed the following code: 
bakta -db ~/Desktop/db Bio1.fsa.gz 
usage: bakta [--db DB] [--min-contig-length MIN_CONTIG_LENGTH]
             [--prefix PREFIX] [--output OUTPUT] [--genus GENUS]
             [--species SPECIES] [--strain STRAIN] [--plasmid PLASMID]
             [--complete] [--prodigal-tf PRODIGAL_TF]
             [--translation-table {11,4}] [--gram {+,-,?}] [--locus LOCUS]
             [--locus-tag LOCUS_TAG] [--keep-contig-headers]
             [--replicons REPLICONS] [--compliant] [--proteins PROTEINS]
             [--skip-trna] [--skip-tmrna] [--skip-rrna] [--skip-ncrna]
             [--skip-ncrna-region] [--skip-crispr] [--skip-cds]
             [--skip-pseudo] [--skip-sorf] [--skip-gap] [--skip-ori] [--help]
             [--verbose] [--debug] [--threads THREADS] [--tmp-dir TMP_DIR]
             [--version]
             <genome>
bakta: error: unrecognized arguments: Bio1.fsa.gz

As you can see at the end, the fsa.gz file is not recognized.  I've tried this with fasta and fsa.  

I also cannot get amrfinderplus into the correct directory?  Where is it supposed to go.  As written, and installed with Conda, nothing is really where it needs to be and the code is not working.  I can call bakta for help but that is about it.

**Comment by oschwengers** [comment]
Hi @KFWins2022 , thanks for reaching out and asking.
If this is not a mere typo here in the issue description, then you might have missed a second dash `-` in the database parameter.
Just try: `bakta --db ~/Desktop/db Bio1.fsa.gz`

**Comment by KFWins2022** [comment]
Hello again! Maybe?  I have this error now

ERROR: database version file (version.json) not readable!

I downloaded the zip file and manulaly dropped it in home/miniconda3/envs/batka/lib/python3.11/site-packages and created a new folder db.  I also installed amrfinderplus via conda and updated it manually.

I feel really dumb as I am new to this and I appreciate your patience.

**Comment by KFWins2022** [comment]
There was absolutely a typo for sure.

FYI I am on a linux system...which is what is foreign to me so I am grateful for any insight you can provide.

**Comment by oschwengers** [comment]
You're welcome! The easiest way, which I would also recommend, is to use Bakta's internal database download logic which takes care of everything including the AMRFinder db: `bakta_db download --output <output-path>`
Just replace `<output-path>` with the desired location of the database for which ~50 Gb are required.

**Comment by KFWins2022** [comment]
I think I got it to work....thank you!!!

**Comment by oschwengers** [comment]
You're very welcome!
