### ISSUE TITLE
error: version.json not readable

### ISSUE THREAD

**Issue by mmcguffi** [oschwengers/bakta#180]
Hi,

Thanks for developing this great tool!

Im trying to run bakta and it's getting hung up at checking the `version.json` file.

I am running bakta on a linux cluster installed via conda (bakta=1.6.1), with a fresh install of the database that completed successfully (`bakta_db download --output bakta_db`).

My command is as follows:
`bakta --debug --db bakta_db --output output/annotation -v assembly.fasta 2> log.log` 

The error in the log file I get is: 
`ERROR: database version file (version.json) not readable!`

This is confusing to me since my permissions of all of the `bakta_db` files are (I did not modify them):
`-r--r--r--`

The contents of the `version.json` file are:
```json
{
  "date": "2022-08-25",
  "major": 4,
  "minor": 0,
  "dependencies": [
    {
      "name": "AMRFinderPlus",
      "release": "2022-08-09.1"
    },
    {
      "name": "COG",
      "release": "2020"
    },
    {
      "name": "DoriC",
      "release": "10"
    },
    {
      "name": "ISFinder",
      "release": "2019-09-25"
    },
    {
      "name": "Mob-suite",
      "release": "2.0"
    },
    {
      "name": "Pfam",
      "release": "35"
    },
    {
      "name": "RefSeq",
      "release": "r213"
    },
    {
      "name": "Rfam",
      "release": "14.8"
    },
    {
      "name": "UniProtKB/Swiss-Prot",
      "release": "2022_03"
    },
    {
      "name": "VFDB",
      "release": "2022-08-19"
    }
  ]
}
```

Any help would be much appreciated! I've also tried setting the environment variable `BAKTA_DB` instead of passing it as an argument, as well as providing absolute path to the database, none of which worked. This seems to somewhat relate to #120, though it seems like our issues were caused by different things I couldn't find a solution there.

**Comment by mmcguffi** [comment]
Of course after hours of debugging and almost immediately after posting this, I found the very simple solution to my problem 🤦‍♂️ Im going to close this, but also going to keep this here in case someone else stumbles across this in the future.

This issue was I needed to point not to folder I created when downloading the database (`bakta_db`), but rather the database folder contained within (`bakta_db/db`)

Thanks again for the great tool!

**Comment by oschwengers** [comment]
Thanks for this follow-up info! ;-)
