### ISSUE TITLE
Is it possible to output RefSeq locus tags?

### ISSUE THREAD

**Issue by ezherman** [oschwengers/bakta#181]
Hi, thank you for releasing and maintaining this awesome software! I was hoping to use this program instead of PGAP, however I am currently running into the following problem: I require locus tags in the output `.gbff` file to match those on RefSeq for my downstream analysis. Is there an option that I have missed, that makes this possible?

**Comment by ezherman** [comment]
Following the recommendation [here](https://github.com/tseemann/prokka/issues/472#issuecomment-598000034), I moved the locus tag into the /product of my genbank file. The locus tag can then be found in the `.gbff` file that bakta returns, under /product.

In case it's of use to anyone else, hereby the python code that formed the basis for this modification:

```
import gzip
from Bio import SeqIO

# moves locus tag to the product key 
# of the qualifiers attribute, as the product key
# is maintained by the downstream bakta annotator
def alter_cds_records(feature):
    qual = feature.qualifiers
    
    if feature.type == "CDS":
        qual["product"] = qual["locus_tag"]
    
    return feature

final_records = []
with gzip.open("input.gbk.gz", "rt") as handle:
    for record in list(SeqIO.parse(handle, "gb")):
        features = record.features 
        altered_features = [alter_cds_records(feat) for feat in features]
        record.features = altered_features
        final_records.append(record)

with open(output.gbk, 'wt') as f:
            SeqIO.write(final_records, f, "genbank")
```

I'll leave this issue open, as a suggestion for an enhancement, however the above modification of the gbk file solves the issue for me.

**Comment by oschwengers** [comment]
Hi @ezherman , thanks for both, the question and answer ;-) I added a new "info" label to tag all these helpful issues containing all sorts of info, knowledge, and code snippets.

Regarding your initial question: As Torsten Seemann stated in the linked answer, new logic is needed since we cannot just transfer locus tags because they are created incrementally at runtime containing all genes - not only CDS.

Again, thanks a lot!
