### ISSUE TITLE
Feature suggestions regarding Expert search and others

### ISSUE THREAD

**Issue by davidtong28** [oschwengers/bakta#183]
Hi Oliver,
Thank you for developing Bakta. I really enjoy using it. I came across some issues while running it, here are some that I find worth reporting:

## Regarding user specified reference genomes
I was recently annotating some *Streptococcus pluranimalium* genomes. I used my reference genome (NCBI accession CP025536.1) in `.gb` format as the user-provided protein database for the `Expert-AA-seq` search. I was expecting that Bakta tells me if the genes had a homology to my reference sequences. In reality I cannot find any signs of this in the `.gff3` file it created. My previous experience tells me that the `.gff3` file copies the `dbxref=` information from the reference sequences. However, this reference that I provided does not have that information. I had to go to the `.json` file to see which genes had a hit to my references. But even that does not give me all the information i wanted. Here is an example.
```
            "id": "LMKFHNBGOL_1202",
            "locus": "LMKFHN_05750"
        },
        {
            "type": "cds",
            "contig": "contig_7",
            "start": 286544,
            "stop": 287680,
            "strand": "-",
            "gene": null,
            "product": "DNA polymerase III subunit beta",
            "start_type": "ATG",
            "rbs_motif": "AGGAG",
            "db_xrefs": [
                "SO:0001217",
                "UniRef:UniRef50_O54376",
                "UniRef:UniRef90_A0A345VGZ9"
            ],
            "frame": 2,
            "aa": "MVSFAINKAFFLHALNATKRAISTKNAIPILSTIKIEVATSGITLTGSNGQISIEHFISVENDNAGLLITSPGAILLEAGFFINIVSSLPDVTLDFKEMANYQVQITSGKSEITLKGKDVEQYPRLQEVDTNNPLSMETKTLKQVITETSFAASTQESRPILTGVHIMLKDNQVFKAVATDSHRMSQRQLNLEKKSADFDVVIPSRSLREFSAVFTDDIENVEIFFSSSQILFRSENISFYTRLLEGAYPDTDRLLTPNFETEVVFKTANLRQAMERAFLVSNATQNGTVKLEITGNAVSAHVNSPEVGKVNEELDVEELSGSDLTISFNPTYLIEALKALKSETVRVRFLSPVRPFTLTPGDDSENFIQLITPVRTN",
            "aa_hexdigest": "bcbb45a31c706ac87c553a9df6d1c693",
            "nt": "ATGGTTTCATTTGCGATTAACAAAGCATTTTTCCTACACGCTCTTAATGCTACAAAAAGAGCTATTTCTACTAAAAATGCTATTCCTATTTTATCAACCATTAAAATTGAAGTTGCGACTTCTGGAATCACTTTAACAGGGTCTAATGGTCAAATTTCAATTGAGCATTTCATTTCAGTCGAAAATGATAATGCTGGCTTGTTGATAACTTCTCCAGGAGCCATTCTTTTGGAAGCTGGTTTCTTCATCAATATCGTATCAAGTCTTCCTGATGTCACTCTTGATTTTAAAGAAATGGCTAACTATCAAGTTCAAATCACAAGTGGAAAATCAGAGATTACACTTAAAGGTAAGGATGTTGAACAATACCCACGTCTTCAAGAAGTTGATACTAATAATCCTTTGAGTATGGAGACTAAAACACTCAAACAAGTCATCACAGAAACGTCATTTGCAGCTAGTACACAAGAAAGTCGTCCTATTTTAACTGGTGTTCACATCATGCTTAAAGATAATCAAGTATTTAAAGCTGTAGCAACAGATTCTCATCGTATGAGTCAACGTCAACTAAATTTAGAGAAAAAATCAGCTGATTTTGATGTTGTTATTCCTAGTCGTTCACTACGTGAATTTTCAGCCGTTTTTACGGATGATATTGAGAACGTAGAGATTTTCTTCTCTTCAAGTCAAATTCTCTTTAGAAGTGAAAATATTAGCTTTTACACACGTCTTCTCGAAGGAGCCTATCCAGATACTGACCGCCTTCTTACCCCTAATTTTGAGACAGAGGTTGTCTTTAAGACCGCCAATCTTCGCCAAGCTATGGAACGTGCTTTCTTGGTGTCAAATGCGACACAAAACGGAACAGTAAAACTTGAAATTACAGGTAATGCAGTCAGTGCTCATGTAAACTCACCAGAAGTCGGAAAAGTTAATGAAGAACTTGACGTGGAAGAGTTGTCAGGAAGTGACTTAACCATTAGTTTCAACCCAACTTATTTGATTGAAGCCCTAAAAGCACTTAAGAGTGAAACTGTTCGCGTTCGCTTCTTATCTCCAGTTCGTCCATTCACTTTAACACCAGGTGATGATAGCGAAAACTTTATTCAACTGATTACACCAGTTCGTACAAACTAA",
            "psc": {
                "uniref90_id": "UniRef90_A0A345VGZ9",
                "query_cov": 1.0,
                "identity": 0.9790000000000001,
                "valid": true,
                "gene": "dnaN",
                "product": "Beta sliding clamp",
                "uniref50_id": "UniRef50_O54376"
            },
            "pscc": {
                "uniref50_id": "UniRef50_O54376",
                "db_xrefs": [
                    "SO:0001217",
                    "UniRef:UniRef50_O54376"
                ],
                "product": "Beta sliding clamp"
            },
            "expert": {
                "user_proteins": {
                    "source": "UserProteins",
                    "rank": 100,
                    "gene": null,
                    "product": "DNA polymerase III subunit beta",
                    "query_cov": 1.0,
                    "model_cov": 1.0,
                    "identity": 0.995,
                    "evalue": 1.08e-263,
                    "bitscore": 712.0
                }
            },
```
In my reference, the "DNA polymerase III subunit beta" looks like:
```
     gene            1632..2768
                     /locus_tag="C0J00_00010"
     CDS             1632..2768
                     /locus_tag="C0J00_00010"
                     /inference="COORDINATES: similar to AA
                     sequence:RefSeq:NP_720489.1"
                     /note="Derived by automated computational analysis using
                     gene prediction method: Protein Homology."
                     /codon_start=1
                     /transl_table=11
                     /product="DNA polymerase III subunit beta"
                     /protein_id="AUW95659.1"
                     /translation="MISFAINKAFFLHALNATKRAISTKNAIPILSTIKIEVATSGIT
                     LTGSNGQISIEHFISVENDNAGLLITSSGAILLEAGFFINIVSSLPDVTLDFKEMANY
                     QVQITSGKSEITLKGKDVEQYPRLQEVDTNNPLSMETKTLKQVITETSFAASTQESRP
                     ILTGVHIMLKDNQVFKAVATDSHRMSQRQLNLEKKSADFDVVIPSRSLREFSAVFTDD
                     IENVEIFFSSSQILFRSENISFYTRLLEGAYPDTDRLLTPNFETEVVFKTANLRQAME
                     RAFLVSNATQNGTVKLEITGNAVSAHVNSPEVGKVNEELDVEELSGSDLTISFNPTYL
                     IEALKALKSETVRVRFLSPVRPFTLTPGDDSENFIQLITPVRTN"
```
As you can see, the `expert` section did not report all the information from the reference. I was still unsure which gene it hits to, since paralogues and hypotheticals are commonly given the same product name in my reference sequences.
Thus, I was wondering if Bakta could report the homologous gene from the reference, preferably in the `locus_tag` or  `protein_id`. Also I apologize if this is already achieved, as I might not have looked closely enough. Thank you.

## Regarding start codon position
I was previously annotating *Campylobacter jejuni* genomes. In *C. jejuni*, there is a common indel mechanism, where the length of poly-G sites are constantly changing, usually ranging from G8 to G11. For example, a site of nine Gs can mutate to ten Gs within a short period of time. These poly-G sites, when located within a CDS, especially at the 3' region, are able to cause frame shifts which fuses the gene with the downstream gene, switching gene product from active to inactive, which is also shown by Bakta. However, I also noticed that when the poly-G sites are located at 5' region within a CDS, Bakta reports that when the indel occurs (and no other mutations in the region), the C terminus tail (from poly-G to stop codon) of the protein are unchanged, but the rather the start codon is relocated, adjusting so that the majority of the gene falls in the correct reading frame. Both +1 and +2 insertions were able to find a different start codon site from the upstream. However I am not sure if this really happened or is it a mistake made by Prodigal. I'd like to know your opinion on the probability of this being a program mistake. If needed, I can provide you with the sequences.

## Regarding database location
Another issue I ran into is the same as #180 . I downloaded to directory `bakta_db download --output ~/bakta/db` but when specifying the database it should be `-db ~/bakta/db/db`. I think it would be nice if Bakta is able to report that the database directory is incorrect rather than the JSON is incorrect. It took me a while to figure out the problem.

Otherwise I really enjoyed using Bakta! I'm looking forward to it shining brighter. Thank you so much.

Sincerely,

David

**Comment by oschwengers** [comment]
@davidtong28 , thanks for these detailed reports!

>Regarding user specified reference genomes

Fair point. I added the model ID (either AMRfinder, expert proteins or user proteins) to the `expert` objects so that each hit can be identified. In addition, I added these model IDs to the `db_xrefs` of each CDS which is exported in the GenBank, EMBL and GFF3 files. Hence, proteins annotated by user provided proteins are marked as such via a `db_xrefs` entry, for example: `UserProtein:JBJEFO_00005`. IDs are either the locus_tag for Genbank files the sequence ID for Fasta files.

>Regarding start codon position

Excellent observation and good catch - thanks a lot! Indeed, it would be very interesting for us to play around with your sequences. The pseudogene detection currently starts with CDSs predicted by prodigal and afterwards, Bakta identifies known protein sequences from the database that can be mapped onto the genomic region in a translated manner. If this seq maps to the majority of the sequence and to its stop codon and in addition onto an upstream start codon, then chances are high that this is a pseudogene with a wrong initial start site. These things are notoriously very hard to classify by automated pipelines.

>Regarding database location

I see. This behavior is due to a couple of tests. First, Bakta checks if the provided DB path exists, if it's a directory and then finally checks the existence of every single database file. The first is `version.json`so if the database path exists but points to the wrong directory, it cannot find the version file. I adopted the error message to provide some hints to other users facing this same thing.
