### ISSUE TITLE
VirulenceFinder database version out of date

### ISSUE THREAD

**Issue by DeenSm** [oschwengers/bakta#184]
Hi Oschwengers, 

I am using bakta to annotate shiga toxin genes, VirulenceFinder database now includes additional stx2 shiga toxin genes up to stx2m. The VirulenceFinder database version currently available through bakta only goes to stx2g and does not include the new variants. 

Please can you update the database version.

**Comment by DeenSm** [comment]
Most up to date version is:
database version: [(2022-12-02)](https://bitbucket.org/genomicepidemiology/virulencefinder_db/)

**Comment by oschwengers** [comment]
Hi @DeenSm , currently, VirulenceFinder is neither part of Bakta nor used within the database compilation process. For the latter we use [VFDB](http://www.mgc.ac.cn/cgi-bin/VFs/v5/main.cgi).

**Comment by DeenSm** [comment]
Hi @oschwengers,

thank you very much for clarifying, my mistake. 

thanks for making bakta, it's now my preferred annotation tool.

**Comment by oschwengers** [comment]
you're welcome and thanks for the heads-up regarding VirulenceFinder!
