### ISSUE TITLE
tRNAscan-SE fails when writing to custom tmp directory

### ISSUE THREAD

**Issue by b-tierney** [oschwengers/bakta#187]
I've found that, inconsistently, tRNAscan-SE fails, throwing the following error (bakta V1.6.1, installed in its own conda environment, tRNAscan-SE V2.0.11, installed alongside the bakta ). Here is an example logfile output:

```
parse genome sequences...
        imported: 1
        filtered & revised: 1
        contigs: 1

start annotation...
predict tRNAs...
Traceback (most recent call last):
  File "/home/btt4001/miniconda3/envs/bakta/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/home/btt4001/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/main.py", line 150, in main
    genome['features'][bc.FEATURE_T_RNA] = t_rna.predict_t_rnas(genome, contigs_path)
  File "/home/btt4001/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/features/t_rna.py", line 70, in predict_t_rnas
    raise Exception(f'tRNAscan-SE error! error code: {proc.returncode}')
Exception: tRNAscan-SE error! error code: 5
```

This most recently occurred with the following command on an HPC system, when running ~80 jobs simultaneously. This was the command used in the slurm file; I specify the tmp directory explicitly to avoid filling up my system's tmp db:

```bakta --threads 8 --tmp-dir "$basename"_tmp  --skip-pseudo --prefix "$basename"_bakta --db /path/to/db $seqfile```

I've experienced this occur multiple times with different datasets, and the samples it affects seem random. Sometimes, rerunning with fixes the issue, other times not. I thought maybe it was a memory error, but after adjusting RAM multiple times saw no change; some samples remained stubborn. It also additionally could be a disk read-write issue unique to my file system.

However, when I switched to this command, it passed the tRNAscan step without error:

```bakta --threads 8 --skip-pseudo --prefix "$basename"_bakta --db /athena/masonlab/scratch/users/btt4001/databases/bakta_db/db $seqfile```

This could be unique to my system or something on the bakta/tRNAscan-SE end, it's still nebulous to me, but I figured it's worth raising. My hypothesis is that it may not be a tRNAscan problem, but rather something with the copying of the contigs file to the tmp directory itself, given that tRNAscan appears to run first.

**Comment by oschwengers** [comment]
Hi @b-tierney , thanks for reporting.
Is this error for a given genome reproducible, *i.e.* can you reproduce it by providing a tmp dir via `--tmp-dir`?
And could you please attach the log file or at least the very end of the log file which should provide `STDOUT` and `STDERR` of tRNAscan-SE.

**Comment by b-tierney** [comment]
Hi -- I might be misunderstanding you, but as far as I can tell, the ```--tmp-dir``` flag seems to be at least correlated to the issue. See above, I tried it with and without, same cores/RAM and getting failure with and success without. That said, I have also seen failures later in the pipeline with the crispr prediction step, haven't gotten to the bottom of it yet.

What I attached above is all I'm getting from the logfile -- I can rerun in debug mode maybe and see what it says then.

**Comment by oschwengers** [comment]
> See above, I tried it with and without, same cores/RAM and getting failure with and success without.

OK, that's a hint

> What I attached above is all I'm getting from the logfile -- I can rerun in debug mode maybe and see what it says then.

Yes, running in `--debug` is def. recommended. However, what you have provided is the normal output to `STDOUT`. There should be a proper log file with a `"$basename"_bakta` prefix and a `.log` suffix. That would be very helpful.

**Comment by oschwengers** [comment]
@b-tierney *friendly ping* Is this still active?

**Comment by oschwengers** [comment]
OK, I'll close this for now. If this is still active and of interest, please, do not hesitate to re-open it.
