### ISSUE TITLE
Adding Userprotein min_identity as command line option

### ISSUE THREAD

**Issue by davidtong28** [oschwengers/bakta#197]
Hi Oliver,

Thank you for updating the new version. I am excited to try it out.
I am trying out the new Userprotein enhancements on Campylobacter genomes. It is working great on close strains but the thresholds are too strict for distant strains. I wanted to loosen the identity and coverage thresholds to annotate more distant strains. However I somehow failed to edit my `.faa` reference to the correct format for Bakta. Specifying the thresholds in the `.gbk` file doesn't seem to make a difference. I was wondering if it is possible to make these thresholds as command line options to simplify the process.

Cheers,
David

**Comment by oschwengers** [comment]
Hi David,
you're right. Bakta filters the user-proteins hits according to the user-provided thresholds for Fasta-provided proteins and standard PSC thresholds for GenBank-provided ones. However, Diamond itself is executed already using the standard PSC thresholds, i.e. 90% sequence identity and 80% mutual query/subject coverage. For closely related proteins, this is just fine but, of course, will exclude hits of more distant sequences.

I'll adjust the internal Diamond thresholds to at least 50% sequence identity and 60% mutual query/subject coverage. This will allow less-tight user-provided thresholds that are used in later filtering steps.

Could you provide some guidance on how distantly related your protein hits are?

**Comment by davidtong28** [comment]
Hi Oliver,
I'm using the C. jejuni NCTC11168 (NC_002163.1) as reference to annotate C. jejuni and C. coli sequences. I am getting ~1400 hits for C. jejuni which I'm happy about, but only ~500 for C. coli.
Using the same reference, the Campylobacter core genome in PUBMLST is 1343 genes. 95% of the genes are commonly shared in C. jejuni and C. coli using thresholds of 50% coverage and 70% BLASTN identity. 
In order to manually adjust my thresholds, do you mind providing a detailed example of the `fasta` file in README?

Cheers,
David

**Comment by oschwengers** [comment]
Hi,
OK, these are fairly relaxed thresholds. So far, I parameterized the searches with stricter thresholds but they seem to be too strict. I'll relax remove the Diamond-based thresholds and relax the default sequence identity threshold to 50%. However, I'm reluctant to further relax the default coverage thresholds since I feel there are good reasons to restrain hits to those having a fairly large overlap. 

These default values are used for imports using the Genbank and short Fasta formats. Via the long Fasta format, you can overwrite these thresholds. There is a description of these formats (maybe hidden the looong readme): https://github.com/oschwengers/bakta#user-provided-protein-sequences

```
# short:
>id gene~~~product~~~dbxrefs
MAQ...

# long:
>id min_identity~~~min_query_cov~~~min_subject_cov~~~gene~~~product~~~dbxrefs
MAQ...
```

So for the long format, e.g. 60% sequence identity, 70% query coverage and 75% subject coverage:
```
>ID 60~~~70~~~75~~~gene~~~product~~~dbxrefs
MAQ...
```

However, as explained before, Diamond is currently executed using 50% seq identity, and 80% query/subject coverage. Therefore, you'd need to wait for the next release which might take a while.

**Comment by davidtong28** [comment]
Thank you! This is really helpful.

**Comment by davidtong28** [comment]
Hi Oliver, I hope you are doing well.
I am still not able to make Bakta recognize my user provided fasta file. Could you help me troubleshoot my syntax?
```
>Cj0001 60~~~50~~~50~~~dnaA~~~chromosomal_replication_initiator_protein~~~EnsemblGenomes-Gn:Cj0001,EnsemblGenomes-Tr:CAL34182,GOA:Q9PJB0,InterPro:IPR001957,InterPro:IPR003593,InterPro:IPR010921,InterPro:IPR013159,InterPro:IPR013317,InterPro:IPR018312,InterPro:IPR020591,InterPro:IPR024633,InterPro:IPR027417
MNPSQILENLKKELSENEYENYLSNLKFNEKQSKADLLVFNAPNELMAKFIQTKYGKKIAHFYEVQSGNKAIINIQAQSA
KQSNKSTKIDIAHIKAQSTILNPSFTFESFVVGDSNKYAYGACKAIAHKDKLGKLYNPIFVYGPTGLGKTHLLQAVGNAS
LEMGKKVIYATSENFINDFTSNLKNGSLDKFHEKYRNCDVLLIDDVQFLGKTDKIQEEFFFIFNEIKNNDGQIIMTSDNP
PNMLKGITERLKSRFAHGIIADITPPQLDTKIAIIRKKCEFNDINLSNDIINYIATSLGDNIREIEGIIISLNAYATILG
QEITLELAKSVMKDHIKEKKENITIDDILSLVCKEFNIKPSDVKSNKKTQNIVTARRIVIYLARALTALTMPQLANYFEM
KDHTAISHNVKKITEMIENDASLKAKIEELKNKILVKSQS
>Cj0002 60~~~50~~~50~~~dnaN~~~DNA_polymerase_III,_beta_chain~~~EnsemblGenomes-Gn:Cj0002,EnsemblGenomes-Tr:CAL34183,GOA:Q0PCC3,InterPro:IPR001001,InterPro:IPR022634,InterPro:IPR022635,InterPro:IPR022637,UniProtKB/TrEMBL:Q0PCC3
MKLSINKNTLESAVILCNAYVEKKDSSTITSHLFFHADEDKLLIKASDYEIGINYKIKKIRVESSGFATANAKSIADVIK
SLNNEEVVLETIDNFLFVRQKSTKYKLPMFNHEDFPNFPNTEGKNQFDIDSSDLSRSLKKILPSIDTNNPKYSLNGAFLD
IKTDKINFVGTDTKRLAIYTLEKANNQEFSFSIPKKAIMEMQKLFYEKIEIFYDQNMLIAKNENFEFFTKLINDKFPDYE
KVIPKTFKQELSFSTEDFIDSLKKISVVTEKMRLHFNKDKIIFEGISLDNMEAKTELEIQTGVSEEFNLTIKIKHLLDFL
TSIEEEKFTLSVNEPNSAFIVKSQGLSMIIMPMIL
```

Cheers

**Comment by davidtong28** [comment]
Hi Oliver,

Thank you for taking time to troubleshoot. You reminded me to seek information in the log file, and I was able to sort it out myself. 
Also I realized that I shouldn't have just copied and pasted a few lines but provide the whole file. See [this link](https://object-arbutus.cloud.computecanada.ca/cidgohshare/eagle/davidtong/nctc11168_bakta.faa) for the whole file.

Here's the error in the log file:
```
ValueError: Wrong dbxref format in Fasta user protein file! dbxref=NA
```

According to the log file, it seems to be complaining about the `dbxref` column. Knowing this hint I found that the problem probably had something to do with me parsing the reference sequences:
```
>NA 60~~~50~~~50~~~NA~~~pseudogene_(putative_IgA_protease_family_protein)~~~NA
```

So any reference sequence without the `dbxref` information would be parsed as `NA`. I suppose I should have used `~~~NA:NA` instead of `~~~NA`. After changing it I was able to complete the annotation :)
This time using a relaxed threshold, I was able to get 1300 user protein hits compared to 500 previously, for more distant species.

Just one more thing out of curiosity, since I used a relaxed threshold this time, I'm wondering what is Bakta's behaviour when one queried gene hits to two user provided protein? Will it report both or will it only report the hit with the highest score?

**Comment by oschwengers** [comment]
> Just one more thing out of curiosity, since I used a relaxed threshold this time, I'm wondering what is Bakta's behaviour when one queried gene hits to two user provided protein? Will it report both or will it only report the hit with the highest score?

For each query protein (from the genome) Bakta will only search for the single best hit.
