### ISSUE TITLE
Compatibility .fna output with NCBI Bankit Submission

### ISSUE THREAD

**Issue by menickname** [oschwengers/bakta#201]
Thanks for this great tool! Very happy with the improvements and performance as compared to available alternatives! To make the tool even more useful and user friendly, I have encountered som small issues.

The .fna files are not submittable as such to the **NCBI Bankit system**. While the .fna output file is of great interest to facilitate and standardize NCBI submissions, current file format is not fully compatible with the submission system. Following (easy to implement?) adjustments/updates would be required to have it immediately submittable:
- [organism=xxx] without the strain information and only genus and species _(does not result in an error on Bankit!)_
- [completeness=complete] automatically added even without including the --complete in the CLI. Not all submitted contigs are necessarily complete _(does not result in an error on Bankit!)_
- [location=chromosome] missing in current .fna files. This is mandatory to be present in at least one of the contigs within the .fna file as per instructions of NCBI submission (https://www.ncbi.nlm.nih.gov/genbank/genomesubmit/) _(error on Bankit!)_
- [plasmid-name=xxx] plasmid name should be unique for each plasmid and should follow the instructions as available in NCBI, nice to automatically include this in the tool or have it specified on the github repository? (https://www.ncbi.nlm.nih.gov/genbank/genomesubmit/#chr_names) _(error on Bankit!)_

Next to that, an additional plus would be to have a separate file with the **expert system proteins** available, including some measures such as nt %ID, AA %ID, query coverage, E-value as this would be of major use in all-in-one interpretation and analyses of the analysed genomic data in an accurate way.

**Comment by oschwengers** [comment]
Hi @menickname, and thanks a lot for all your suggestions. I'll have a look at it ASAP. Submission rules and guidelines are constantly changing, so it's subject to constant maintenance and updates. Thanks a lot for the heads-up and details.

**Comment by oschwengers** [comment]
1. should be fixed by https://github.com/oschwengers/bakta/commit/4e2017e7da03f82217c0521d5e3027820e6b2f1c

**Comment by oschwengers** [comment]
4. should now be addressed by https://github.com/oschwengers/bakta/commit/8cd3d15c61df90dd1d4d199929090609be55f981

**Comment by oschwengers** [comment]
3. is also addressed by https://github.com/oschwengers/bakta/commit/af835b4313d3cb5931d68616d71d0d2623d13afc.

I'll close this. Just in case there is anything missing, please do not hesitate to re-open it.
Best regards!
