### ISSUE TITLE
Bakta_proteins connection to dbxrefs/json-type identifier

### ISSUE THREAD

**Issue by Rridley7** [oschwengers/bakta#204]
Hello, thanks again for your work on this tool! I wanted to suggest a possibility for when using `bakta_proteins`, to output the `dbxrefs` and/or some sort of connection to the more feature rich information given when annotating via the normal mode of bakta. Even if this was all output into a tsv format as is already the case, with an additional dbxrefs list column, it would be very useful for seeing where annotations initiate from (eg AMRFinder, UniProt, etc.).

**Comment by oschwengers** [comment]
Hi @Rridley7,
I'm not sure if we should change the `TSV` format by adding another column and thus introduce a breaking change.
To provide the detailed information on all hits and `dbxrefs`, I've added an additional `bakta_proteins` JSON output file in line with the main version. I hope this is sufficient for your needs?

**Comment by Rridley7** [comment]
This should work great, thank you!
