### ISSUE TITLE
Add the ability to annotate only one's own database

### ISSUE THREAD

**Issue by famiji** [oschwengers/bakta#208]
**Describe the solution you'd like**
Add the ability to annotate only one's own database

Hello author, thank you for your work. I am a novice in bioinformatics. During the research process, I need to annotate specific genes in the sequence to facilitate the study of their upstream and downstream relationships and visualize it. The only prokaryotic annotation tools I know of are prokka and bakta, as well as the online tool RAST. However, it seems that none of these three tools have the ability to annotate only genes that users provide . I would like to know if bakta can add this feature. （If Bakta already has this feature, please forgive my ignorance）

**Comment by oschwengers** [comment]
Hi @famiji and thanks for reaching out.
You're right, Bakta doesn't have such a feature. You can provide your own annotation sequences via the `--proteins` parameters, so Bakta will use these with top priority. However, this will not hinder the software from using other sources from the internal DB, as well. Such a feature is currently not planned. 
Best regards!
