### ISSUE TITLE
User proteins fasta file formatting issue

### ISSUE THREAD

**Issue by EGTortuero** [oschwengers/bakta#209]
I was running Bakta to reannotate a Pseudomonas aeruginosa genome and I tried to use a user proteins fasta file for such step. The command used was:

bakta --db /home/egtortuero/db-light -p LESB58_reannotated -o LESB58_BAKTA --genus Pseudomonas --species aeruginosa --strain LESB58 --complete --locus LES --proteins LESB58_DB.BAKTA.faa --compliant PaeLESreseq.fa

However, I retrieved the following error:

ERROR: User proteins file Fasta format not valid!

So, I checked how it should be formatted and it seems that the format is the correct one:
>PLES_00001 dnaA~~~chromosomal replication initiator protein DnaA~~~EnsemblGenomes-Gn:PLES_00001,EnsemblGenomes-Tr:CAW24728,GOA:B7V0N6,InterPro:IPR001957,InterPro:IPR003593,InterPro:IPR010921,InterPro:IPR013159,InterPro:IPR013317,InterPro:IPR018312,InterPro:IPR020591,InterPro:IPR024633,InterPro:IPR027417
MSVELWQQCVDLLRDELPSQQFNTWIRPLQVEAEGDELRVYAPNRFVLDWVNEKYLGRLLELLGERGEGQ
LPALSLLIGSKRSRTPRAAIVPSQTHVAPPPPVAPPPAPVQPVSAAPVVVPREELPPVTTAPSVSSDPYE
PEEPSIDPLAAAMPAGAAPAVRTERNVQVEGALKHTSYLNRTFTFENFVEGKSNQLARAAAWQVADNLKH
GYNPLFLYGGVGLGKTHLMHAVGNHLLKKNPNAKVVYLHSERFVADMVKALQLNAINEFKRFYRSVDALL
IDDIQFFARKERSQEEFFHTFNALLEGGQQVILTSDRYPKEIEGLEERLKSRFGWGLTVAVEPPELETRV
AILMKKAEQAKIELPHDAAFFIAQRIRSNVRELEGALKRVIAHSHFMGRPITIELIRESLKDLLALQDKL
VSIDNIQRTVAEYYKIKISDLLSKRRSRSVARPRQVAMALSKELTNHSLPEIGVAFGGRDHTTVLHACRK
IAQLRESDADIREDYKNLLRTLTT

I also tested removing the "~~~" symbols by three spaces, but it does not work. Am I missing something wrong with the user protein fasta formatting, please?

Thanks in advance!

Enrique

**Comment by oschwengers** [comment]
Dear Enrique,
I checked your snippet and the Bakta format is indeed correct. But the starting `>` is missing in the header. Once I added this to your example, it worked just fine.
