### ISSUE TITLE
`bakta_db download` downloads database every time it is run 

### ISSUE THREAD

**Issue by geboro** [oschwengers/bakta#210]
`bakta_db download` will download the database each time is run, no matter if there is an existing version of the database in the target defined by the `--output` directory. 

It would be optimal that the database does not get downloaded if it already exist in the target directory. In my case, it keeps failing because of the AMRFinder database update, and then when rerun it needs to download the full 33Gb database, making it very hard do debug.

**Comment by oschwengers** [comment]
Hi @geboro, I totally see your point. Inthese cases it might be best to manually setup the database as described in the readme:

```bash
wget https://zenodo.org/record/7669534/files/db.tar.gz
tar -xzf db.tar.gz
rm db-light.tar.gz
amrfinder_update --force_update --database db/amrfinderplus-db/
```

By this you can re-use the installed database for debugging purposes. Also, you could think of downloading the `light` database version. To do so, just add the `--type light` parameter.
