### ISSUE TITLE
conda installs version 1.3.1 while latest is 1.7

### ISSUE THREAD

**Issue by splaisan** [oschwengers/bakta#213]
The anaconda page says the current version is 1.7 (same in the github release page), however, conda installs 1.3.1

I did the following:

```
git clone https://github.com/oschwengers/bakta.git
cd bakta
conda env create -f environment.yml
conda activate bakta
conda install -c bioconda bakta

$ bakta --version
bakta 1.3.1
```

Now trying to upgrade manually to v1.7 with:

```
conda install -c bioconda bakta==1.7
```

seems to have worked, the conda recipe is probably not pointing to the right version by default:

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    alive-progress-3.0.1       |     pyhd8ed1ab_0          62 KB  conda-forge
    bakta-1.7.0                |     pyhdfd78af_1          96 KB  bioconda
    ------------------------------------------------------------
                                           Total:         157 KB
```

I now have the version 1.7 and ```bakta_db list```  now gives the right database link

```
$ bakta_db list
Bakta software version: 1.7.0
Required database schema version: 5

Available DB versions:
5.0     2023-02-20      10.5281/zenodo.7669534
```

**Comment by oschwengers** [comment]
Hi,
I think this is related to Conda and its internal tool management and dependency solving algo. If possible, the easiest thing is to create a new environment installing the required packages with distinct versions, e.g.:

`conda create -p <local-path-to-env> bakta=1.7.0`

**Comment by oschwengers** [comment]
@splaisan I'll close this for now. Just in case, this issue is not related to Conda itself and remains, please do not hesitate to re-open it. Best regards!
