### ISSUE TITLE
Rare extended-ascii character in product field breaks ascii-only tools

### ISSUE THREAD

**Issue by axbazin** [oschwengers/bakta#215]
Hi,

Lately we've had multiple issues from users using Bakta to annotate their genomes (as they should ;-) ) here: https://github.com/labgem/PPanGGOLiN/issues/95 

The product string of recD seems to contain an extended ascii character which is the "acute accent" (https://www.ascii-code.com//180 ), to talk about strand orientation in the product field.

Should we deal with non-ascii characters when reading protein annotations, or is there possibly a latin1 or unicode character that sneaked in one of the databases you use and shouldn't be there?

Adelme

**Comment by dvallenet** [comment]
Hi

The "accute accent" is from this COG entry:
https://www.ncbi.nlm.nih.gov/research/cog/cog/COG0507/

David

**Comment by oschwengers** [comment]
Thanks @axbazin and @dvallenet for the heads-up. I'll take a look at it.

**Comment by oschwengers** [comment]
OK, this should be fixed by https://github.com/oschwengers/bakta/commit/4e0b3071d7bc6548b31921a3b242dca4faabac7a

I plan a new release next week delivering a couple of recent fixes.

Again, thanks for reporting!
Oliver

**Comment by axbazin** [comment]
Thank you so much for such a rapid fix !

Adelme

**Comment by oschwengers** [comment]
Should not happen anymore in https://github.com/oschwengers/bakta/releases/tag/v1.8.0

**Comment by Nilad** [comment]
Re-open.

https://github.com/labgem/PPanGGOLiN/issues/95

**Comment by oschwengers** [comment]
thanks for the heads-up-

**Comment by oschwengers** [comment]
@Nilad, As I just posted in https://github.com/labgem/PPanGGOLiN/issues/95 I'm still not sure how to fix this. And in addition, I'm a bit reluctant to add unique string fixes to the Bakta code for each wrong COG annotation - who knows, how many of them will occur next?

I'm sorry that I cannot provide more help in this case. But, I do hope, the next COG version will be released, soon ;-)
