### ISSUE TITLE
re-allow biopython 1.78

### ISSUE THREAD

**Issue by alexweisberg** [oschwengers/bakta#217]
The conda install of Bakta previously allowed versions of biopython < 1.80 until a recent change (https://github.com/bioconda/bioconda-recipes/pull/39675). I was wondering if it would be possible to relax that requirement again? 

I ask because I have bakta in a few conda recipes along with a number of other programs that require biopython == 1.78, such as antismash and integron_finder. It seems the main reason for the update is the new plotting feature which uses gc_fraction, which was introduced in 1.80. Given bakta works with 1.78 when --skip-plot is used, could this requirement be relaxed again? Or a detection of the version to see if this function could be used? It would be nice to be able to continue to include recent versions of bakta in the conda environment. Thanks!

**Comment by oschwengers** [comment]
Tweaked in merged PR #218
