### ISSUE TITLE
bakta encounters issues annotating assemblies with presence of N's

### ISSUE THREAD

**Issue by plaquette** [oschwengers/bakta#222]
hey, i have some assemblies that i want to annotate.

it works fine when
 - i annotate using prokka
 - remove the N's by hand

but fails with ``` ERROR: genome file (test.fa) not valid! ``` when there are N's in the sequences. 

i use  bakta v1.7.0 installed via conda and call it like this:

``` bakta --db db-light --verbose --output test --locus test --locus-tag test --threads 10 --skip-plot --strain test --complete test.fa ```

one example is attached (now with .txt extension instead of .fa - i was not allowed to upload it with the original extension):
[test.txt](https://github.com/oschwengers/bakta/files/12037758/test.txt)

concluding from this issue #87 it should work with the N's
... what can i do to fix this?

Thank you very much!

Best,

j.

**Comment by oschwengers** [comment]
Hi @plaquette,
thanks for reporting. Unfortunately, I cannot reproduce this issue. I tested your file with Bakta `v1.8.1` and `v1.7.0`, and both worked just fine. There was once an issue with `-` within sequences (#87) but this is not related to `N`s, they should work just fine.

This leaves me a bit puzzled. Could you execute Bakta in `--debug` mode and provide the logs?

**Comment by plaquette** [comment]
hey @oschwengers - sorry for the very delayed answer, i was on vacation.

it seems, that i can not reproduce my errors from last month... 

therefore the issue can be closed. sorry for bothering you & thank you.

best,

p.
