### ISSUE TITLE
Swap tRNAscan-SE model to general

### ISSUE THREAD

**Issue by Serka-M** [oschwengers/bakta#225]
Hello and thank you for developing Bakta, it's a great tool!

One minor improvement that I would like to suggest is to swap the tRNAscan-SE model from bacterial ("-B" flag) to general ("-G" flag).

Our group has observed on several occasions that the swap allows to detect slightly more tRNAs in bacterial MAGs that otherwise might be missed by the "bacterial-only" model.

Cheers!

**Comment by oschwengers** [comment]
Hi @Serka-M ,
thanks for sharing these results and bringing this up - very interesting! I wonder if this higher sensitivity is traded by lower specificity? For example, have you compared predicted `tRNA` locations within isolate genomes between `-B` and `-G`? I feel a bit reluctant to swap these parameters in general. Of course, it could make sense for the `--meta` mode. Maybe a large and tax. broad comparison would be beneficial, so we do not change predicted `tRNA`s for isolates - which is still the majority of annotated genomes, I guess. 
Hence, could you maybe underpin this with some convincing statistics?

Anyways, again, thanks a lot!
Cheers!

**Comment by Serka-M** [comment]
Hello again, 
Looks like I've made an error of analyzing bacterial and archaeal MAGs in the same batch.
For anyone interested, in a dataset of 10 000 bacterial MAGs, the `-G` model would detect more tRNAs in only approx. 0.5 % of cases. 
Meanwhile for archaeal MAGs, the `-G` model would pick up more tRNAs approx 64 % of the time (1 000 archaeal MAG dataset)
