### ISSUE TITLE
gene missing from final output files

### ISSUE THREAD

**Issue by AthinaGav** [oschwengers/bakta#226]
I am running bakta on a number of files and in a downstream analysis I noticed a strange gap among the genes. I searched in the genbank and protein fasta files and indeed there is **one gene missing completely** from all output files. 

In the log file however (see also attached), I can see that the gene is detected:
_11:32:42.451 - INFO - CDS - contig=BGC0001459, start=7068, stop=9020, strand=+, frame=3, truncated=no, start-type=ATG, RBS-motif=GGAG/GAGG
**11:32:42.451 - INFO - CDS - contig=BGC0001459, start=9023, stop=18490, strand=+, frame=2, truncated=no, start-type=ATG, RBS-motif=GGAGG**
11:32:42.451 - INFO - CDS - contig=BGC0001459, start=18975, stop=31166, strand=+, frame=3, truncated=no, start-type=ATG, RBS-motif=GGAG/GAGG_
[dec_1.log](https://github.com/oschwengers/bakta/files/12250421/dec_1.log) 

When I run the analysis on debug mode, I can see the gene in the following temporary files:
cds.expert.faa                    cds.spurious.faa                      diamond.cds.expert.tsv

The **command** I am using looks like this:
_bakta --db <dbpath> --output baktaresult --threads 30 --prefix <prefix> --locus bgc1459  --locus-tag bgc1459 --keep-contig-headers BGC0001459.fna_

I have installed bakta with **conda**

This actually happened with multiple of my files - though not all - always on this specific gene (topologically, though the files are not identical). 
Any suggestions on how to solve this would be much appreciated. Please let me know if there is any other information that would be useful.

**Comment by oschwengers** [comment]
Hi, thanks for reporting.
There is a `tmRNA` gene encoded within your `CDS` of interest. By default, Bakta discards als `CDS` that spanning `tRNA` or `tmRNA` as this should occur only in rare cases. If you're sure that this `CDS` is a real gene and the ``tmRNA` might be a false positive, you could simply skip the tmRNA-prediction via `--skip-tmrna`.

**Comment by AthinaGav** [comment]
Indeed that was the case. Since I am more interested in any potential CDS and not so much in any tRNA or rmRNA, i skipped both those predictions and everything seems in order now. Thank you for your help!
