### ISSUE TITLE
get database version for custom db path

### ISSUE THREAD

**Issue by jotech** [oschwengers/bakta#228]
I would like to check the version of the bakta database, which I downloaded successfully using `bakta_db download`.
However, `bakta_db list` doesn't work because I chose a default database path (`bakta_db download --output ...`).

**Describe the solution you'd like**
`bakta_db list` should take the `--db` parameter as input to list the respective database version.

**Describe alternatives you've considered**
I tried `bakta_db list --db` ... or `bakta_db list --output ...`. Both didn't work.

**Comment by oschwengers** [comment]
Thanks for this idea. I'll consider another `bakta_db` command to provide this local DB info.

But the `bakta_db list` will only provide a list of database versions that are available online.
Meanwhile, to check the version of your downloaded DB, you can either open the `version.json` file, or you can just use this DB with `bakta -v --db ...` and Bakta will print the DB info to the console and to the logs.

**Comment by jotech** [comment]
Thank you for considering it and for mentioning `version.json`. I will go for it!
