### ISSUE TITLE
Docker container: Open shell or run command other than "bakta", such as "bakta_db"

### ISSUE THREAD

**Issue by MrTomRod** [oschwengers/bakta#233]
**Describe the bug**

I found it confusing to run the Docker container.

### Examples

**1) Download database:** `podman run -it --rm -v .:/data:Z oschwengers/bakta bakta_db download --output /data/bakta-light.db --type light`

Result:
```
usage: bakta [--db DB] [--min-contig-length MIN_CONTIG_LENGTH] [--prefix PREFIX] [--output OUTPUT] [--force]
             [--genus GENUS] [--species SPECIES] [--strain STRAIN] [--plasmid PLASMID] [--complete]
             [--prodigal-tf PRODIGAL_TF] [--translation-table {11,4}] [--gram {+,-,?}] [--locus LOCUS]
             [--locus-tag LOCUS_TAG] [--keep-contig-headers] [--replicons REPLICONS] [--compliant]
             [--proteins PROTEINS] [--meta] [--skip-trna] [--skip-tmrna] [--skip-rrna] [--skip-ncrna]
             [--skip-ncrna-region] [--skip-crispr] [--skip-cds] [--skip-pseudo] [--skip-sorf] [--skip-gap]
             [--skip-ori] [--skip-plot] [--help] [--verbose] [--debug] [--threads THREADS] [--tmp-dir TMP_DIR]
             [--version]
             <genome>
bakta: error: unrecognized arguments: download --type light
```

**2) Open shell:** `podman run -it --rm -v .:/data:Z oschwengers/bakta bash`

Result:

```
ERROR: database neither provided nor auto-detected!
Please, download the mandatory db and provide it via either the --db parameter, a BAKTA_DB environment variable or copy it into the Bakta base directory.
For further information please read the readme.md
```

These messages are a bit confusing. The reason is that the image has an **Entrypoint**.

### Workaround

The entrypoint can be overridden, e.g. like this:

```bash
podman run -it --entrypoint=/bin/bash --rm -v .:/data:Z --workdir /data oschwengers/bakta
```

### Recommendation

I think the container would be better if the [Entrypoint](https://github.com/oschwengers/bakta/blob/main/Dockerfile#L52) were not specified. I see more disadvantages than advantages, but maybe I'm wrong, of course.

**Comment by oschwengers** [comment]
Thanks @MrTomRod for this. I agree, that for experienced users, this is not the optimal setting. The self-maintained Docker image specifies an entrypoint to make its usage easier for non-cli / container experts.

I updated the [readme](https://github.com/oschwengers/bakta#podman-docker) pointing to the [Biocontainer](https://quay.io/repository/biocontainers/bakta?tab=tags) images that do not specify an entrypoint and thus can be used to execute the `bakta_db` and `bakta_proteins` commands, as well: 

```bash
export CONTAINER="quay.io/biocontainers/bakta:1.8.2--pyhdfd78af_0"
podman run -it --rm $CONTAINER bakta --help
podman run -it --rm $CONTAINER bakta_db --help
```

Again, thanks a lot. I'll close this for now. Please do not hesitate to re-open it in any case. Best regards!
