### ISSUE TITLE
Installation of bakta on Google Colab

### ISSUE THREAD

**Issue by lagerstefanie** [oschwengers/bakta#234]
Hi,

It would be nice if it was possible to install bakta on Google Colab. I have tried to install it using conda, but it crashes when trying to solve environment.

**Comment by oschwengers** [comment]
Hi @lagerstefanie,
I have no experience with Google Colab so far. Could you please elaborate a bit more on what you have done how (commands) and also provide the exact error message (or better the entire log) of Conda?

**Comment by lagerstefanie** [comment]
I installed conda (worked fine):

!pip install condacolab
import condacolab
condacolab.install_miniconda()

and then just ran:

!conda install -c conda-forge -c bioconda bakta
But that just get stuck on "Solving environment" for several hours!

As an alternative I tried to follow the instructions how to install Trinity on Colab (# Updating Conda, # Appending python packages to the sys.path etc) before trying to install bakta using conda, but that didn't help.
https://www.linkedin.com/pulse/how-install-run-conda-google-colab-ambu-vijayan

**Comment by oschwengers** [comment]
OK, could you please try Mambaforge? This will significantly speed-up the entire process and maybe also help to solve the environment dependencies:

```
!pip install condacolab
import condacolab
condacolab.install_mambaforge()
!mamba install -c conda-forge -c bioconda bakta
```

Also, by using `conda install` you install Bakta within your current existing environment. If Mambaforge doesn't help, then you most certainly have existing packages that collide with the dependencies of the Bakta package. In this case, you'd need to either remove the problematic existing packages or you create a fresh new Conda environment for Bakta and the activate this new one.

**Comment by lagerstefanie** [comment]
Thank you,

Mambaforge  seems to solve the problem, at least bakta installs without complain and seems to work (-h works), I still need to download DB and run. But I think it works now!
