### ISSUE TITLE
Cannot run bakta with biocontainer image

### ISSUE THREAD

**Issue by Swarnali3** [oschwengers/bakta#236]
**Describe the bug**
I tried running bakta with the following command:

docker run -it --rm  quay.io/biocontainers/bakta:1.8.2--pyhdfd78af_0  bakta  --db  ./db-light  ./genome.fasta

The db-light and genome.fasta was in the current working directory. But, I got the error:
ERROR: wrong database path! --db=./db-light

How to enter the correct path for the bakta database while running the docker image?

**Comment by oschwengers** [comment]
Hi @Swarnali3 ,
thanks for asking. Running a container, you need to mount all required system volumes into the container. The provided docker or podman wrapper scripts do this automatically to hide these container specific parameters as described in the readme. 

For all Docker related questions, may I kindly refer you to the official docs: https://docs.docker.com/get-started/06_bind_mounts/
