### ISSUE TITLE
Update to pyrodigal v3

### ISSUE THREAD

**Issue by jsgounot** [oschwengers/bakta#240]
**Describe the bug**

Current bakta version does not support pyrodigal v.3.0.0, which is automatically installed with a default conda install.

Error message:

```
start annotation...
predict tRNAs...
        found: 0
predict tmRNAs...
        found: 0
predict rRNAs...
        found: 0
predict ncRNAs...
        found: 0
predict ncRNA regions...
        found: 1
predict CRISPR arrays...
        found: 0
predict & annotate CDSs...
Traceback (most recent call last):
  File "condafolders/envs/bakta/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "condafolders/site-packages/bakta/main.py", line 228, in main
    cdss = feat_cds.predict(genome, contigs_path)
  File "condafolders/site-packages/bakta/features/cds.py", line 41, in predict
    orffinder = pyrodigal.OrfFinder(meta=prodigal_metamode, closed=closed)
AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'
```

I downgraded my version to follow your pip instruction with pyrodigal=2.1 and it seems to work

Fixes: 
* Change the conda recipe to force pyrodigal=2.1
* Update bakta code to accommodate new pyrodigal version.

Thanks for your tool.
JS

**Comment by oschwengers** [comment]
Thanks a lot @jsgounot for reporting.
A [fix](https://github.com/oschwengers/bakta/commit/b38f279360c65c8e31e243879a11514ffb77db43) is already committed. As soon as https://github.com/bioconda/bioconda-recipes/pull/43097 is merged, this error should be gone.

Thanks and best regards!

**Comment by oschwengers** [comment]
Ok, the patch is live. 

`mamba create -p conda-test-env -d bakta=1.8.2` installs Pyrodigal `2.3.0` - seems to work then.

Thanks again!
