### ISSUE TITLE
Is it possible to import my own cds fasta file for annotation?

### ISSUE THREAD

**Issue by PengfanZhang** [oschwengers/bakta#245]
Hi, I have my own cds file predicted from `prodigal` with customized translation table. I'm wondering if `bakta` offers the option to annotate user-specified cds files rather than starting from scratch?

**Comment by oschwengers** [comment]
Hi @PengfanZhang , thanks for asking. Unfortunately, this is currently not possible. As this is asked for more and more often, we might consider implementing this - however, we cannot provide any reasonable ETA.

**Comment by oschwengers** [comment]
Ok, since more and more users ask for a feature like this, I've started a new issue #250 collecting ideas and requirements. Feedback and input is highly welcome!

**Comment by oschwengers** [comment]
OK, with #250 I'd consider this as addressed. You can now provide CDS coordindates as GFF/Genbank via `--regions` and if required or desired, in addition, provide accompanying functional information via `--proteins`.

Just in case there are any questions or unaddressed use cases, please, do not hesitate to re-open this or another issue.
