### ISSUE TITLE
Merge summary files into one excel sheet.

### ISSUE THREAD

**Issue by AhmedElsherbini** [oschwengers/bakta#246]
Hello, firstly thanks for your nice tool.

For me, as I work with many genomes per run, I just needed a simple feature, which is just merging the summary txt files into one simple Excel sheet. I have already made this simple [script](https://github.com/AhmedElsherbini/Bakta_stats/tree/main) named Bakta_stats. I hope it will be easy to use and offer any help to any colleague with similar need.

**Comment by oschwengers** [comment]
Hi @AhmedElsherbini ,
thanks for reaching out and your script. Your issue triggered me to add a general script collection directory, see #251 . For mere code maintenance, I re-implemented your script and added another I've written some time ago.

So, thanks a lot!
I'll close this for now, but please, do not hesitate to re-open it just in case, this does not fit your needs or anything else.
Best!

**Comment by AhmedElsherbini** [comment]
Thank you very much for your reply. 
Kindly, if my script was somehow helpful for you, I would be very grateful for any kind of acknowledgment or reference (up to you). I was also  thinking of converting the output of this script into some graphical abstract, as simple as Python matplotlib boxplots or as complex as MultiQC HTML output.

**Comment by oschwengers** [comment]
Of course, proper acknowledgments are self-evident ;-) I normally give credits to everyone somehow involved in the description of each release.
