### ISSUE TITLE
Increasing genome annotation: integrating StORF-Reporter functionality into bakta

### ISSUE THREAD

**Issue by Dx-wmc** [oschwengers/bakta#254]
Hi, I recently read about the StORF-Reporter software published on NAR (https://github.com/NickJD/StORF-Reporter), which can be used to find genes between genes. The author of this software has already included the batka format in its design, but the newly predicted genes lack functional annotations. Can their functionality be integrated into bakta and annotated after predicting all CDS? This would greatly improve the accuracy of CDS prediction and ensure the integrity of gene function.

In addition, to differentiate from the original bakta annotation, I would suggest that a --storf option could be added. Once enabled, it will add new CDS for StORF and annotate them. The newly generated file can be distinguished by adding a suffix of "StORF".

**Comment by oschwengers** [comment]
Hi, thanks a lot for the heads-up - very interesting!
We're already considering taking inter-gene regions into account for an expanded pseudogene detection. However, I see the point that valid genes might also be missing. The suggested approach would require a lot of additional features and code branches, thus, I'd rather address to via a new parameter that I have on my list to include user-provided CDS regions -> #250 

Region information of CDS that have been detected by StORF could then be passed on to a 2nd run of Bakta.

I guess this would be the more flexible approach.

**Comment by Dx-wmc** [comment]
I am looking forward to Bakta performing better.

**Comment by oschwengers** [comment]
Hi @Dx-wmc ,
now that there's [v1.9.0](https://github.com/oschwengers/bakta/releases/tag/v1.9.0) accepting user-provided `CDS` regions, I'd close this issue. If this still does not fit your usecase or requirement, please do not hesitate to open another issue.

Thanks for reaching out and reporting!
Best regards!
