### ISSUE TITLE
bakta is renaming input contigs in its outputs

### ISSUE THREAD

**Issue by splaisan** [oschwengers/bakta#258]
Dear Oliver,

I ran bakta using your latest docker (bakta 1.8.2) and found when visualising various results in IGV that the original Flye contigs had been renumbered/renamed by bakta in the annotation files to arbitrary 1/2/3 indices.

Is this intended and how can I prevent it? I have mapped data which I want to show side by side with annotations and this is not going to work well.

Thanks for your feedback

input fasta assembly:

```
contig_1	6356	10	60	61
contig_3	3971673	6482	60	61
contig_4	87384	4044360	60	61
```

bakta fna file

```
contig_1	6356	138	60	61
contig_2	3971673	6736	60	61
contig_3	87384	4044742	60	61
```

**Comment by splaisan** [comment]
Maybe I can use --replicon and a minimalist table to force the names to the original flye contig names?!

**Comment by oschwengers** [comment]
Hi @splaisan,
If you only would like to keep the original contig IDs, then simply setting `--keep-contig-headers` should work.

There are some other parameters that might be interesting/helpful. You can find a full description here: https://github.com/oschwengers/bakta#usage

Please, do not hesitate to ask, if there are any further questions.

**Comment by splaisan** [comment]
How could i mis this one, i definitely have to read the usage more carefully 🤣

**Comment by oschwengers** [comment]
You're welcome ;-)
