### ISSUE TITLE
Bakta fails using --regions if a sequence does not contain a valid start codon

### ISSUE THREAD

**Issue by NicolasNaepflin** [oschwengers/bakta#262]
Hi,

I have a bunch of gff3 files I obtained from prodigal and would like to annotate the predicted sequences from prodigal using Bakta (version 1.9.1). 
I used the following command with --regions:

```
bakta --db db --prefix test --output test --skip-trna --skip-tmrna \
--skip-rrna --skip-ncrna --skip-ncrna-region --skip-crispr \
--skip-pseudo --skip-sorf --skip-gap --skip-ori --skip-plot --threads 16 \ 
--regions 104623_SAMN02470747_GCA_000463345.gff 104623_SAMN02470747_GCA_000463345.faa
```

And obtained the following error:
`ERROR: User-provided regions/features file GFF3 format not valid!`
 
The log file gave some more information about the issue with the following error:
```
raise CodonTable.TranslationError(
Bio.Data.CodonTable.TranslationError: First codon 'TAT' is not a start codon

ValueError: User-provided CDS could not be translated into a valid amino acid sequence! contig=contig_1, start=4971674, stop=4971757, cds=TATATCTTTCAATTCGTAGGTGTGTTGGTTGTAGTGCTCCTAATTATTGAAGATGTAGTAAATATTCTATTCCGTGTTCTCTGA
```
The corresponding entry in the gff file (from prodigal) confirms, that this sequence does not contain one of the start codons prodigal considers (ATG,GTG,TTG) but rather start_type=Edge
```104623_SAMN02470747_GCA_000463345_1	Prodigal_v2.6.3	CDS	4971674	4971757	2.7	-	0	ID=104623_SAMN02470747_GCA_000463345_04430;partial=01;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.321;conf=64.78;score=2.65;cscore=-0.07;sscore=2.72;rscore=0.00;uscore=0.00;tscore=3.22;prev_ID=104623_SAMN02470747_GCA_000463345_1_4430```

So far, I manually excluded such predicted sequences and Bakta finishes without any issues.

Would there be any way to include an option to skip these with a warning rather then terminating or to force the processing?

I noticed, that the file provided with `--regions` is a bit differently processed (https://github.com/oschwengers/bakta/blob/24a43b9d137cc0d210f6a98ed526b3cc63d66e7e/bakta/features/cds.py#L224C1-L224C31)
```
aa = str(Seq(nt).translate(table=cfg.translation_table, cds=True))
```
than CDS predicted by pyrodigal using Bakta (without the `cds=True`flag).

https://github.com/oschwengers/bakta/blob/24a43b9d137cc0d210f6a98ed526b3cc63d66e7e/bakta/features/cds.py#L122

Thank your for your help.

Best

Nicolas

For completeness I attach the files I was using:
[example_files.zip](https://github.com/oschwengers/bakta/files/13658704/example_files.zip)

**Comment by oschwengers** [comment]
Hi @NicolasNaepflin ,
thanks for reaching out and this detailed report. In fact, I added the `cds=True` option on purpose to check and make sure, that provided nt sequences can be properly translated into valid aa sequences. And in this example this seems to work out as expected.

However, I see the case that it might be hindering to fail on each occasion. However, it forces users to provide only valid CDS. Hence, this is a question of the overall software design. Personally, I'm a huge fan of _failing fast_ approaches, but I see that skipping over single sequences (log warnings) and then proceeding might help to get the job done.

I have to think about this a bit more about this.

**Comment by NicolasNaepflin** [comment]
Hi @oschwengers 

I can see your point of forcing users to provide valid CDS/ failing fast .

Thanks again for the clarification that this was on purpose.

**Comment by oschwengers** [comment]
OK, I'll close this for now. If there is anything new to consider like more users having issues with this or more valid cases where the _failing fast_ approach is hindering, please do not hesitate to re-open this or a new issue.
