### ISSUE TITLE
Exception: diamond error! error code: -11

### ISSUE THREAD

**Issue by jjpadilla1987** [oschwengers/bakta#271]
I am trying to annotate multiple genomes and used bakta since I already used this tool before and it worked well and gave out the best results compared to other tools. However, I have been encountering problems lately when running the analysis, I already tried to re-install bakta but it didnt work. Here's the code i used:

bakta --db /work/jpadilla/conda/envs/bakta/db --prefix 2008Ycf657 --output bakta_2008Ycf657 --genus Burkholderia --species cenocepacia --strain 2008Ycf657 --complete --keep-contig-headers --compliant --force --translation-table 11 --threads 20 2008Ycf657.fna

And here's is the error I got:

parse genome sequences...
        imported: 3
        filtered & revised: 3
        chromosomes: 3

start annotation...
predict tRNAs...
        found: 70
predict tmRNAs...
        found: 1
predict rRNAs...
        found: 18
predict ncRNAs...
        found: 33
predict ncRNA regions...
        found: 23
predict CRISPR arrays...
        found: 0
predict & annotate CDSs...
        predicted: 6815
        discarded spurious: 1
        revised translational exceptions: 1
        detected IPSs: 6517
Traceback (most recent call last):
  File "/work/jpadilla/conda/envs/bakta/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/work/jpadilla/conda/envs/bakta/lib/python3.10/site-packages/bakta/main.py", line 259, in main
    cdss_psc, cdss_pscc, cdss_not_found = psc.search(cdss_not_found)
  File "/work/jpadilla/conda/envs/bakta/lib/python3.10/site-packages/bakta/psc.py", line 64, in search
    raise Exception(f'diamond error! error code: {proc.returncode}')
Exception: diamond error! error code: -11

**Comment by simone-pignotti** [comment]
Hi, I am running into the same issue. Downgrading Diamond from 2.1.9 (released last week) to 2.1.8 has solved the problem for me, but looking at the changelog for 2.1.9 I don't see any breaking changes which might be at the root of this...

**Comment by oschwengers** [comment]
Thanks @simone-pignotti for the heads-up.
@jjpadilla1987 could you check, if downgrading Diamond to `v2.1.8` solves the error in case, as well?

**Comment by jjpadilla1987** [comment]
Hi @simone-pignotti and @oschwengers,

Thanks for the suggestions. I installed diamond 2.1.8 and the analysis worked!

**Comment by pcrxn** [comment]
I'm experiencing the same error when attempting to analyze [GCA_003339035.1](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_003339035.1/), and I can also confirm that downgrading Diamond to `v2.1.8` fixes the error. See [bakta_diamond-2.1.9.stdout.txt](https://github.com/oschwengers/bakta/files/14184633/bakta_diamond-2.1.9.stdout.txt) and [bakta_diamond-2.1.8.stdout.txt](https://github.com/oschwengers/bakta/files/14184635/bakta_diamond-2.1.8.stdout.txt) attached.

**Comment by oschwengers** [comment]
FYI, this bug is occuring in Diamond and it has been reported upstream. A downgrade to `v2.1.8` is currently the best we can do until this is fixed.

https://github.com/bbuchfink/diamond/issues/785

**Comment by oschwengers** [comment]
FYI: I temporarily pinned Diamond to `v2.1.8` in the Bakta Bioconda package: https://github.com/bioconda/bioconda-recipes/pull/46111
