### ISSUE TITLE
circos legend

### ISSUE THREAD

**Issue by 3between7** [oschwengers/bakta#278]
Why is there no legend in the genome circle diagram? How to add legend ?Thanks!

**Comment by joao1980** [comment]
Hi, and thanks for the tool. 
I would also be interested in the legend. Would it b quicker to just add numbers inside the circos plot and place the legends outside of the rings?
Cheers,
Joao

**Comment by oschwengers** [comment]
FYI: I just merged a new branch replacing Circos by pyCirclize. Triggered by this, I also added a legend to Bakta's genome plots and added further parameters to the `bakta_plot` command to customize plots.

You can find some examples at [/examples](https://github.com/oschwengers/bakta/tree/main/examples)

For instance an entire [genome](../blob/main/examples/plot-features-genome.png)
or a single [plasmid](../blob/main/examples/plot-cog-p2.png) with CDS colored by COG functional categories.

I close this for now. Just in case, please do not hesitate to re-open this or a new one.
