### ISSUE TITLE
Color coding in bakta_plot --type cog

### ISSUE THREAD

**Issue by deminatanja** [oschwengers/bakta#280]
Hi,
Do colors in the plots produced with bakta_plot --type cog correspond to this pallete https://help.ezbiocloud.net/cog-colors/ ? If not, could you please provide a source where to find the color coding by COG categories?
Best regards,
Tatiana

**Comment by oschwengers** [comment]
Hi @deminatanja,
thanks for reaching out with this. No, I don't this that we adopted the ezibiocloud colours. I cannot quite remember what was the source of the colour palette, I think we copied it from some internal scripts.
It's not perfect, but you can copy the color codes and descriptions from here: https://github.com/oschwengers/bakta/blob/d6443639958750c3bece5822e84978271d1a4dc7/bakta/plot.py#L40

I'm sorry that we don't have a more user-friendly version of it but I hope it does help at least a bit.

**Comment by deminatanja** [comment]
Hi @oschwengers,
Thanks a lot for the answer! This really helps! :)
Best,
Tatiana

**Comment by priscalim00** [comment]
Hi! Is it possible to have the legend indicate the cog-classes instead of the features? I've tried playing around with the config.yaml file but can't seem to get it to work! Thanks :)

**Comment by priscalim00** [comment]
> The web version of bakta shows the cog-color-legend for the circular plots. You can visualize your bakta json files there: https://bakta.computational.bio/viewer

Oh thank you so much! I didn't know about this web version :)
