### ISSUE TITLE
Downgrading dependencies is needed when installing bakta from conda

### ISSUE THREAD

**Issue by LeonCharlesTranchevent** [oschwengers/bakta#283]
**Issue**
I installed bakta v1.8.2 via conda, the installation was successful but bakta was not operational (it fails and provides an error message - see below). I compared that environment with an older environment (same bakta version) that runs fine and realized that it might be related to some dependencies.

**Command, log and error message**

```
$ bakta --db /nfs/data/db/baktadb_v5/db ~/test.fna --meta --keep-contig-headers --skip-trna --skip-tmrna --skip-rrna --skip-ncrna --skip-ncrna-region --skip-crispr --skip-gap --skip-ori --threads 2 --output ~/ --prefix test_bakta --force 

parse genome sequences... 
        imported: 1 
        filtered & revised: 1 
        chromosomes: 1 
 
start annotation... 
skip tRNA prediction... 
skip tmRNA prediction... 
skip rRNA prediction... 
skip ncRNA prediction... 
skip ncRNA region prediction... 
skip CRISPR array prediction... 
predict & annotate CDSs... 
        predicted: 4365 
        discarded spurious: 8 
        revised translational exceptions: 0 
        detected IPSs: 4264 
Traceback (most recent call last): 
  File "/nfs/conda/envs/testtoremove/bin/bakta", line 10, in <module> 
    sys.exit(main()) 
  File "/nfs/conda/envs/testtoremove/lib/python3.10/site-packages/bakta/main.py", line 253, in main 
    cdss_psc, cdss_pscc, cdss_not_found = psc.search(cdss_not_found) 
  File "/nfs/conda/envs/testtoremove/lib/python3.10/site-packages/bakta/psc.py", line 64, in search 
    raise Exception(f'diamond error! error code: {proc.returncode}') 
Exception: diamond error! error code: -11 
```

**Solution**
After a few trials and errors, I downgraded _diamond_ from v2.1.9 to v2.1.8 and _ncbi-amrfinderplus_ from v3.12.8 to v3.11.26 and could successfully use bakta v1.8.2. I did not check all versions in between for _ncbi-amrfinderplus_.

**Note**
The error was reproduced with different input files - file content does not appear to matter much.

The problem seems to also extend the latest version (v1.9.3 as of last week), although I did not fully test that version (and therefore did not identify which downgrades were required).

**Comment by mmcguffi** [comment]
I also ran into this with Bakta 1.6.1 via conda

based on what @LeonCharlesTranchevent said (thanks for documenting!), but I also had to pin `biopython` -- here is a pinned yaml that worked for me:
```yaml
name: annotation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bakta=1.6.1
  - diamond=2.1.8
  - ncbi-amrfinderplus=3.11.26
  ```
  
  I also had to update the `AMRFinderPlus`s internal database, here is that cmd for convenience: 
  ```bash
amrfinder_update \
    --force_update \
    --database ${database_loc}/db/amrfinderplus-db
```


And of course, thank you @oschwengers for creating such a great tool

**Comment by mmcguffi** [comment]
I also ran into this with Bakta 1.6.1 via conda

Building on what @LeonCharlesTranchevent said (thanks for documenting!), I also [had to pin biopython](https://github.com/nextgenusfs/funannotate/issues/1000) -- here is a pinned yaml that worked for me:
```yaml
name: annotation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bakta=1.6.1
  - diamond=2.1.8
  - ncbi-amrfinderplus=3.11.26
  - biopython=1.8.1
  ```
  
  I also had to update the `AMRFinderPlus`s internal database, here is that cmd for convenience: 
  ```bash
amrfinder_update \
    --force_update \
    --database ${database_loc}/db/amrfinderplus-db
```


And of course, thank you @oschwengers for creating such a great tool

**Comment by oschwengers** [comment]
Hi and thanks for reporting both issues and potential solutions! 

There is an issue with Diamond in `v2.1.9`  and downgrading to `v2.1.8`should do the trick until there is an upstream patch for Diamond.

Regarding AMRFinderplus: They recently updated its database scheme. Best you can do is to update both AMRFinderplus _and_ its database as @mmcguffi suggested.

@mmcguffi Is there a specific issue with BioPython? If so, could you please open a dedicated issue for that? I wasn't aware of that. 

Again, thanks for reporting and documenting!
