### ISSUE TITLE
Roary is not working with bakta-generated gff3-files

### ISSUE THREAD

**Issue by LindavdGvB** [oschwengers/bakta#284]
Roary is not working with the gff3-files generated with Bakta whereas Roary works well with the by Prokka generated gff3 files. 
The roary warning is: 
2024/04/24 10:55:41 Fixing input GFF files

--------------------- WARNING ---------------------
MSG: ##feature-ontology header tag parsing unimplemented
---------------------------------------------------
2024/04/24 10:55:43 Input files have identical MD5 hashes, only using the first file

There are two issues about this on the Roary github site, but since Roary works well with the Prokka generated gff3 files, I assume that this is an issue of Bakta. 
https://github.com/sanger-pathogens/Roary/issues/598
https://github.com/sanger-pathogens/Roary/issues/583

**Comment by oschwengers** [comment]
@LindavdGvB , thanks for reporting. Could please try to install Roary in a fresh conda environment? There are reports that this seems to be related to outdated Perl packages that Roary depends on. As we have successfully tested Roary with Bakta generated GFF3s in the past, I guess it's actually an issue with Roary and older Perl packages than a Bakta issue.

**Comment by dclmjrf** [comment]
I think this warning is related to the second line of the gff3-file generated with Bakta.

```
##gff-version 3
##feature-ontology https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/v3.1/so.obo
```

When I replaced "##" with "# ", the warning disappeared.

```
##gff-version 3
# feature-ontology https://github.com/The-Sequence-Ontology/SO-Ontologies/blob/v3.1/so.obo
```
