### ISSUE TITLE
PSC failed! diamond-error-code=-11

### ISSUE THREAD

**Issue by DariaGI** [oschwengers/bakta#290]
Hello, please help me to resolve the problem below. Where to find information about the -11 diamond error. 

15:11:43.788 - INFO - CDS - contig=contig_16, start=1047, stop=2303, strand=+, nt=[TTGCAAAAAT..CGGCTCTTAA]
15:11:43.789 - INFO - CDS - contig=contig_17, start=897, stop=1418, strand=-, frame=3, truncated=no, start-type=ATG, RBS-motif=None
15:11:43.789 - INFO - CDS - contig=contig_17, start=1544, stop=2563, strand=+, frame=2, truncated=no, start-type=ATG, RBS-motif=None
15:11:43.789 - INFO - CDS - contig=contig_17, start=2560, stop=2781, strand=-, frame=2, truncated=no, start-type=ATG, RBS-motif=None
15:11:43.789 - INFO - CDS - contig=contig_17, start=897, stop=1418, strand=-, nt=[ATGAAATATA..CGTACAATGA]
15:11:43.789 - INFO - CDS - contig=contig_17, start=1544, stop=2563, strand=+, nt=[ATGATAATAG..AAGTAGCTAA]
15:11:43.789 - INFO - CDS - contig=contig_17, start=2560, stop=2781, strand=-, nt=[ATGGACAGAG..AAGTCTTTAG]
15:11:43.789 - INFO - CDS - contig=contig_18, start=357, stop=1025, strand=-, frame=1, truncated=no, start-type=GTG, RBS-motif=GGA/GAG/AGG
15:11:43.789 - INFO - CDS - contig=contig_18, start=357, stop=1025, strand=-, nt=[GTGTCTGCGG..AAAGAAGTAA]
15:11:43.789 - INFO - CDS - contig=contig_19, start=101, stop=454, strand=+, frame=2, truncated=no, start-type=TTG, RBS-motif=GGA/GAG/AGG
15:11:43.789 - INFO - CDS - contig=contig_19, start=101, stop=454, strand=+, nt=[TTGCAAAAAA..TAAAAAATAG]
15:11:43.789 - INFO - CDS - contig=contig_21, start=56, stop=550, strand=-, frame=2, truncated=no, start-type=TTG, RBS-motif=None
15:11:43.789 - INFO - CDS - contig=contig_21, start=56, stop=550, strand=-, nt=[TTGTCTAAAA..TACAACATAA]
15:11:43.839 - INFO - CDS - predicted=689
15:11:43.841 - INFO - ORF - write internal aa seqs: # seqs=689, path=/tmp/tmp_r2ni0o_/cds.spurious.faa
15:11:44.355 - INFO - ORF - discarded=0
15:11:44.411 - INFO - UPS - looked-up=0
15:11:44.412 - INFO - IPS - looked-up=0
15:11:44.412 - INFO - ORF - write internal aa seqs: # seqs=689, path=/tmp/tmp_r2ni0o_/cds.psc.faa
**15:11:52.909 - WARNING - PSC - PSC failed! diamond-error-code=-11**
15:11:52.911 - INFO - MAIN - removed tmp dir: /tmp/tmp_r2ni0o_

I tried to start the annotation with different genomes and the result is the same, so the issie is not related with data. And the diamond itself works fine.

**Comment by kiranpatil222** [comment]
I also have same Error
