### ISSUE TITLE
Diamond Error -9

### ISSUE THREAD

**Issue by cloeme** [oschwengers/bakta#292]
Hi my error code is as below:

Traceback (most recent call last):
  File "/data/cephfs/punim1258/chloe/new_rnaseq2024/bakta/myenv/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/data/cephfs/punim1258/chloe/new_rnaseq2024/bakta/myenv/lib/python3.10/site-packages/bakta/main.py", line 259, in main
    cdss_psc, cdss_pscc, cdss_not_found = psc.search(cdss_not_found)
  File "/data/cephfs/punim1258/chloe/new_rnaseq2024/bakta/myenv/lib/python3.10/site-packages/bakta/psc.py", line 64, in search
    raise Exception(f'diamond error! error code: {proc.returncode}')
Exception: diamond error! error code: -9

Ive tried running two separate genomes of bacteria and still the same error. I have plenty of memory and running this via Unix system (Spartan Unimelb)

Here were the steps to how I loaded Bakta:
# Clone the bakta repository
git clone https://github.com/oschwengers/bakta.git

# Go into the bakta directory
cd bakta

# Copy FASTA file for your bacterial genome to conda environment
cp /data/cephfs/punim1258/chloe/new_rnaseq2024/4496_refgenome.fasta /data/cephfs/punim1258/chloe/new_rnaseq2024/bakta/myenv/

#load Anaconda or Miniconda module
module load Anaconda3/2024.02-1

#create a new conda environment
conda create -p /data/cephfs/punim1258/chloe/new_rnaseq2024/bakta/myenv

#Run conda init in terminal
conda init

#source the updated file
source ~/.bashrc

#activate environment will show (base) at the front of script
conda activate /data/cephfs/punim1258/chloe/new_rnaseq2024/bakta/myenv

### the above steps creates the conda environment for running analysis /
#any packages installed while this environment is ACTIVE will be installed here specifically not affecting my base or other environments

# Add the Bioconda channel
conda config --add channels conda-forge

# Install Bakta packages
conda install bakta

# Download the Bakta database
bakta_db download --output /data/cephfs/punim1258/chloe/new_rnaseq2024/bakta/myenv --type full

# Navigate to the directory containing your fasta file
cd /data/cephfs/punim1258/chloe/new_rnaseq2024/bakta/myenv

# Run the bakta tool on your fasta file
bakta --db /data/cephfs/punim1258/chloe/new_rnaseq2024/bakta/myenv/db 4496_refgenome.fasta --output /data/cephfs/punim1258/chloe/new_rnaseq2024/bakta/myenv/bakta_output --force

Thanks in advance for the help

Chloe

**Comment by oschwengers** [comment]
Hi,
thanks for reporting. Have you already read and checked the issues/solutions provided here: https://github.com/oschwengers/bakta/issues/290 ?

**Comment by oschwengers** [comment]
OK, could you run Bakta setting the `--debug` flag and provide me the `*.log` file for a deeper look into this? And if possible, the genome file would also help to reproduce this error.
