### ISSUE TITLE
pyrodigal has no attribute 'OrfFinder'

### ISSUE THREAD

**Issue by sebibarLE** [oschwengers/bakta#298]
I installed the latest version of Bakta using conda (conda install -c conda-forge -c bioconda bakta) and the full database on 2024-06-27.
I used the following command: 
 bakta --db /home/sebastian/db/ --output results/ --threads 32 Genome.fasta

The following happens:

parse genome sequences...
        imported: 172
        filtered & revised: 172
        contigs: 172

start annotation...
predict tRNAs...
        found: 115
predict tmRNAs...
        found: 1
predict rRNAs...
        found: 18
predict ncRNAs...
        found: 10
predict ncRNA regions...
        found: 79
predict CRISPR arrays...
        found: 3
predict & annotate CDSs...
Traceback (most recent call last):
  File "/home/sebastian/miniconda3/bin/bakta", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sebastian/miniconda3/lib/python3.12/site-packages/bakta/main.py", line 228, in main
    cdss = feat_cds.predict(genome, contigs_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sebastian/miniconda3/lib/python3.12/site-packages/bakta/features/cds.py", line 40, in predict
    orffinder = pyrodigal.OrfFinder(meta=prodigal_metamode, closed=closed)
                ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'

What can I do?

**Comment by oschwengers** [comment]
Hi, in this case you seem to have an older version of Pyrodigal installed. You have to update Pyrodigal to >= `3.0`

**Comment by miaroig** [comment]
I have the same issue 'pyrodigal' has no attribute 'OrfFinder'. My pyrodigal version is 3.4.1, bakta version 1.8.2, 
parse genome sequences...
	imported: 367
	filtered & revised: 367
	contigs: 367

start annotation...
predict tRNAs...
	found: 54
predict tmRNAs...
	found: 1
predict rRNAs...
	found: 3
predict ncRNAs...
	found: 10
predict ncRNA regions...
	found: 18
predict CRISPR arrays...
	found: 0
predict & annotate CDSs...
Traceback (most recent call last):
  File "/home/dwn-63/Apps/mamba/envs/ensamblaje/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/home/dwn-63/Apps/mamba/envs/ensamblaje/lib/python3.10/site-packages/bakta/main.py", line 228, in main
    cdss = feat_cds.predict(genome, contigs_path)
  File "/home/dwn-63/Apps/mamba/envs/ensamblaje/lib/python3.10/site-packages/bakta/features/cds.py", line 41, in predict
    orffinder = pyrodigal.OrfFinder(meta=prodigal_metamode, closed=closed)
AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'
Bakta finished for CEL7_final_assembly.fasta

**Comment by thh32** [comment]
Same issue here, updated pyrodigal to the latest version and still occurs.

**Comment by oschwengers** [comment]
@thh32 @miaroig the newer Pyrodigal version is only supported since Bakta version >= `1.9.0`. Could you please update Bakta and check if the error remains?

**Comment by rubmc97** [comment]
Same issue here, already tried to update bakta and the same error still pops up.

**Comment by oschwengers** [comment]
There is a mutual dependency limitation between Bakta and Pyrodigal.
- Bakta version < [1.9.0](https://github.com/oschwengers/bakta/releases/tag/v1.9.0) requires Pyrodigal version <= [2.3.0](https://github.com/althonos/pyrodigal/releases/tag/v3.0.0)
- Bakta version >= [1.9.0](https://github.com/oschwengers/bakta/releases/tag/v1.9.0) requires Pyrodigal version >= [3.0.0](https://github.com/althonos/pyrodigal/releases/tag/v3.0.0)

Since version [1.9.0](https://github.com/oschwengers/bakta/releases/tag/v1.9.0) Bakta's Conda package has a dependency specification, unfortunately, before it has not. I guess this is the source of this issue, since in older Bakta Conda package versions Pyrodigal can be updated beyond the supported version.

**Comment by oschwengers** [comment]
@sebibarLE @miaroig @thh32 @rubmc97 
I just released [v1.9.4](https://github.com/oschwengers/bakta/releases/tag/v1.9.4) with a potential fix for this issue. Could you please give it a try (best in a fresh Conda env)? Thanks!

**Comment by miaroig** [comment]
Solved by uninstalling and reinstalling bakta and its dependencies

**Comment by oschwengers** [comment]
OK, I tentatively assume that this issue is fixed and thus, close this issue.

Just in case these issues remain after updating Bakta to `v1.9.4` in a fresh Conda env, @sebibarLE @thh32 @rubmc97 , please do not hesitate to re-open this.

**Comment by rubmc97** [comment]
Sorry for being annoying. pyrodigal seems to be working but now I have an issue with tRNA-SE... "Traceback (most recent call last):
  File "/home/comi/ruben.martinez/miniconda3/envs/bakta-env/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/home/comi/ruben.martinez/miniconda3/envs/bakta-env/lib/python3.10/site-packages/bakta/main.py", line 155, in m$    genome['features'][bc.FEATURE_T_RNA] = t_rna.predict_t_rnas(genome, contigs_path)
  File "/home/comi/ruben.martinez/miniconda3/envs/bakta-env/lib/python3.10/site-packages/bakta/features/t_rna.py", line$    raise Exception(f'tRNAscan-SE error! error code: {proc.returncode}')
Exception: tRNAscan-SE error! error code: 2". I'm using the bakta version 1.9.4. If I run it alone like trnascan-SE -h and with conda list, it seems to be there and working, but keep getting this error when running bakta. Thanks!

**Comment by oschwengers** [comment]
Hi, this error seems to be unrelated to the Pyrodigal/Pyhmmer error. May I kindly as to open a new issue and provide the log file of a `--debug` run?
