### ISSUE TITLE
Bakta web version ignores translation table change 

### ISSUE THREAD

**Issue by AggressiveHayBale** [oschwengers/bakta#305]
**Description**
Accessing the current version of web version of Bakta (Software: 1.9.1| DB: 5.0.0)  and selecting Translational table: 4: The Mold... results in the Bakta execution on the default table 11, ignoring the selection. 

**Step to replicate**
Annotate the genome while changing the translational table 11 to 4. 

**Output**
The output json reports:

```
{
    "genome": {
        "genus": null,
        "species": null,
        "strain": null,
        "complete": true,
        "gram": "?",
        "translation_table": 11
    }
```

I assume somewhere in the web version code either referring to this parameter is overwritten or the selection in the web GUI goes nowhere (I couldn't find the code related to the web code in the repo).

**Comment by oschwengers** [comment]
Hi @AggressiveHayBale ,
thanks a lot for reporting. I'll copy/forward this to the right repo (https://github.com/ag-computational-bio/bakta-web-ui) and close it here, since it's addressing the web version and not the CLI version itself.
