### ISSUE TITLE
reproducibility - amrfinderplus-db

### ISSUE THREAD

**Issue by Juke34** [oschwengers/bakta#306]
I ran bakta on database from 2023 and got this error message

```
Exception: amrfinder error! error code: 1. Please, try 'amrfinder_update --force_update --database /share/banks/bakta_db_2308/db/amrfinderplus-db' to update AMRFinderPlus's internal database.
```

The thing is for reproducibility reason I want to continue to work with my "old" version of amrfinderplus-db. 
Is there any way to pass by that limitation? If not it should definitely possible to use the wished version of the DB.

Best regards

**Comment by marade** [comment]
My initial runs with the latest amrfinderplus-db yield far fewer results than with previous versions. I wonder if that's why you want to use the older version @Juke34 ?

**Comment by oschwengers** [comment]
In principle, this is not an "issue" with Bakta, but with AMRFinderPlus which changed its internal db format. Thus, newer versions of AMRFinderPlus require a DB update. If you'd like to use an older Bakta DB version (with an older version of the AMRFInderPlus db within), you need to assure that you also use an older version of AMRFinderPlus. You can read more about this in the [AMRFinderPlus](https://github.com/ncbi/amr) repository. I guess you need to downgrade it to something before `v3.12.8`  -> https://github.com/ncbi/amr/releases

**Comment by Juke34** [comment]
Hi @marade, nothing related to quality/quantity of the results, just matter about be reproducible according to an ancient run.

@oschwengers thank you for your answer, I understand better now.

**Comment by marade** [comment]
FYI, I found I was losing AMR results because the JSON annotation had changed to list format for those entries. Somehow I missed that update.
