### ISSUE TITLE
Option for trusted HMMs

### ISSUE THREAD

**Issue by StefDiV** [oschwengers/bakta#309]
**Is your feature request related to an existing issue or bug?**
Similar to #295, using hmm instead of a protein set.

An option like: "--hmms: Trusted HMM to first annotate from (default '')" from prokka, so the user can provide a custom hmm or hmm database that bakta could use to derive annotation first and its not overlapped by following annotation steps.

Example: given a particular protein of interest which has been used to create and curate a hmm, bakta could take the hmm (with defined cutoff scores) to identify it first in the dataset and the annotation is preserved in the final outputs.

**Comment by oschwengers** [comment]
Hi @StefDiV ,
thanks for reaching out with this. This is certainly a great idea and a feature that Bakta is currently missing. I'll put this on my lis. Hopefully for the next version, but I cannot promise yet.

**Comment by oschwengers** [comment]
OK, now, this is implemented and live in the main branch. If you like, you can give it an early try. This will be part of the upcoming `v1.10.0` release.

Again, thanks a lot @StefDiV for bringing this up! If you have any feedback, comments or further ideas, please do not hesitate to re-open this or file a new issue.

**Comment by StefDiV** [comment]
@oschwengers thank you so much for implementing the feature! Just passing by to share that it works great with both single hmm files and pressed hmm databases. Small note for other users, when using self-generated hmms, make sure to also include the ACC field in the header section, in hmmbuild it is optional but without it bakta returns an error.
