### ISSUE TITLE
tRNAscan-SE issue on HPC

### ISSUE THREAD

**Issue by Sylvia-li** [oschwengers/bakta#311]
parse genome sequences...
        imported: 1
        filtered & revised: 1
        contigs: 1

start annotation...
predict tRNAs...
Traceback (most recent call last):
  File "/opt/conda/bin/bakta", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/bakta/main.py", line 155, in main
    genome['features'][bc.FEATURE_T_RNA] = t_rna.predict_t_rnas(genome, contigs_path)
  File "/opt/conda/lib/python3.8/site-packages/bakta/features/t_rna.py", line 70, in predict_t_rnas
    raise Exception(f'tRNAscan-SE error! error code: {proc.returncode}')
Exception: tRNAscan-SE error! error code: 2

Bakta container runs fine on the login node, but when I run the image on an HPC node i get tRNAscan-SE error code:2. I checked a previous similar error (error code 2) which had to do with /tmp/ directory - I have tried the option --tmp-dir and set it to different directory but it still outputs 
Unable to open /local/syl218/932130/tscan861346.fpass for writing.  Aborting program. 
which is not the temporary directory i set in bakta. I do not think the warning about locale matters as running it on the login node is fine and the debug file still has that warning.

tRNAscan-SE by itself is fine, it runs fine on the HPC login node

- Which commands have been executed and what exactly happened
Ran 
salloc --mem=32G
singularity run /globalhome/syl218/HPC/bakta.sif sample2.contigs_medaka.fa.gz --min-contig-length 200 --threads 1 --prefix sample1.bakta --db ~/h_somni/nfs/APL_Genomics/db/prod/bakta/db/ --debug

- Detailed logs (execute Bakta with `--debug`)
[sample1.bakta.log](https://github.com/user-attachments/files/16532409/sample1.bakta.log)

- How did you install Bakta: `Conda`, `Pip`
singularity build bakta.sif docker://oschwengers/bakta:latest

Thank you. I really am not sure what to do

**Comment by oschwengers** [comment]
Thanks @Sylvia-li for reporting. 

1. TMP: `tRNAscan-SE` does not offer a parameter to specify its temporary directory (or have I missed something?) Hence, we cannot forward the user-provided Bakta tmp to `tRNAscan-SE`
2. It seems, that there is an issue with your Perl locale setting. Unfortunately, I don't have enough Perl skills to point you to a solution. As this is the first error report of this kind, I tend to conclude that this is more an individual issue with your specific Conda environment and HPC setup. Maybe a local admin can help?

I'm sorry, that I cannot provide more help here.

**Comment by fischuu** [comment]
I am facing a similar problem and stuggle still with a solution, but in your case @Sylvia-li , have you tried to bind the path of the tmp folder to your singularity call? Like, adding the option -B /locale:/locale to the singularity call, I suppose the problem is that the singularity container cannot access the tmp folder, when it is not mounted/bound to it?

**Comment by Sylvia-li** [comment]
> I am facing a similar problem and stuggle still with a solution, but in your case @Sylvia-li , have you tried to bind the path of the tmp folder to your singularity call? Like, adding the option -B /locale:/locale to the singularity call, I suppose the problem is that the singularity container cannot access the tmp folder, when it is not mounted/bound to it?

@fischuu thank you so much, It works now! Really, thank you! appreciate it.

**Comment by oschwengers** [comment]
Thanks for jumping in @fischuu, just in case you're still struggling with tRNAScan, please do not hesitate to open a new issue describing your case. 

Thanks and best regards!
