### ISSUE TITLE
conda install did not install bakta_db

### ISSUE THREAD

**Issue by JCSzamosi** [oschwengers/bakta#313]
I followed the instructions to install bakta using conda, and it appears to have successfully installed, but the program `bakta_db` is absent (`which bakta_db` returns nothing) and I don't see another way to install it.

Was it supposed to install with bakta? And if not, how do I install it? Or do I not need it as long as I download the databases and can provide bakta with the path to them?

**Comment by fraser-combe** [comment]
You need to read the database download section on the bakta main page. you have light or full db version. the conda env does not download

**Comment by JCSzamosi** [comment]
Thanks for your response! Just to clarify, I don't mean the database itself is missing. The program `bakta_db`, which you say to use to download the databases, was not installed with the conda installation. I was able to download the databases manually and run bakta, just thought I would let you know those instructions don't work if a person has used the conda installation instructions.

**Comment by oschwengers** [comment]
Thanks @JCSzamosi for reporting. Unfortunately, I cannot reproduce this. I leave this open for a while, just in case others are facing the same issue.
