### ISSUE TITLE
option to include scores in bakta output

### ISSUE THREAD

**Issue by jvera888** [oschwengers/bakta#314]
Hi,

Bakta is a superb annotation tool, so thanks for all the hard work! However, there does not appear to be a way to include any annotation scores (e.g. evalue, percent identity, etc) in the output (e.g. Dfast does this), unless I'm missing something very obvious (not unheard of).

I realize not everyone wants their genbanks and GFFs cluttered up with this extra info, but an option to have these included in some way would be great for those of us who need that extra level of certainty.

Thanks,
Cris

**Comment by gbouras13** [comment]
This would be super duper useful I think, especially as a separate `.tsv` file :)

George

**Comment by oschwengers** [comment]
OK, this is implemented in #331 . Thanks again for the idea, comments and feedback!

**Comment by jvera888** [comment]
this is a bit late but thanks for adding this feature!  I've already added the new info to my pipeline :)
