### ISSUE TITLE
Missing genes in both faa files

### ISSUE THREAD

**Issue by EdderDaniel** [oschwengers/bakta#317]
Hi! 

I ran the standard annotation instruction with bakta 1.9.4 (installed with conda) and after looking at the outputs i noticed that some genes are missing from the faa files (hypotheticals and regular faa file), but present in all of the other annotation files, which is really odd, because if it reported in the gbff there should't be a reason why they are not included in the faa, rigth? Or is there a reason for this?

**Comment by oschwengers** [comment]
Hi @EdderDaniel ,
thanks for reporting, and yes, if this is reproducible, then it's indeed odd and not intended. Hence, could you provide a genome sequence for a reproducible example? I'd love to take a closer look into this.

**Comment by EdderDaniel** [comment]
Sure! I'm sending you a tar.gz file with the fna, tsv, faa, log and gbff. the genome that i used is Aetokthonos_hydrillicola_CCALA_1050, which i got from NCBI and the bakta options that are use were  meta compliant  and keep-contig-headers

Thanks for the help!


[Aetokthonos_hydrillicola_CCALA_1050.tar.gz](https://github.com/user-attachments/files/16845641/Aetokthonos_hydrillicola_CCALA_1050.tar.gz)

**Comment by EdderDaniel** [comment]
Hi Oliver! Just dropping by to say that i´ve been looking into this and it appears that the missing genes are always RNA related (ribosomal, tRNA, etc...). Maybe that´ll help to pinpoint the bug?

**Comment by oschwengers** [comment]
Hi. Haven't looked into it yet, but if you can already assure that all missing genes are actually RNA genes, then they should be excluded from the *.faa files for a good reason since they're not translated.

If this explanation is too obvious - then in that case, I'm sorry and I might be missing something.

**Comment by EdderDaniel** [comment]
Ha! No, you are completely right. For some reason i confounded faa and ffn in my mind. I´ll close the issue now. Sorry for the confusion!
