### ISSUE TITLE
AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'

### ISSUE THREAD

**Issue by cuongngh** [oschwengers/bakta#319]
**Describe the bug**
To fix any bugs and issues and also to help other users who might face the same issues, a concise description is beneficial and often necessary.

Therefore, please provide us with at least the following information:

- Which commandos have been executed and what exactly happened
- Detailed logs (execute Bakta with `--debug`)
- How did you install Bakta: `Conda`, `Pip`

Hi, I run bakta locally and has this error: AttributeError: module 'pyrodigal' has no attribute 'OrfFinder'. I tried to run pyrodigal separately and it works fine. Could you please help me to fix this? I installed pyrodigal separately because I have Mac with Apple silicon. Thanks so much.

**Comment by oschwengers** [comment]
Hi @cuongngh, this seems to be caused by an unsupported Pyrodigal version. I'd like to kindly refer you to https://github.com/oschwengers/bakta/issues/298 which deals with exactly this problem and provides a description/solution.

**Comment by cuongngh** [comment]
> Hi @cuongngh, this seems to be caused by an unsupported Pyrodigal version. I'd like to kindly refer you to #298 which deals with exactly this problem and provides a description/solution.

@oschwengers, thank you so very much for the information.

**Comment by Sarani-NS** [comment]
Hi @cuongngh , did you manage to fix it ? I checked the #298 issue but I guess it doesn't apply, as I downloaded Bakta using Conda today only, so everything should be up to date & all dependencies installed. I still get the same error. Any lead ?
Thanks in advance,

**Comment by Sarani-NS** [comment]
Hi @cuongngh , I am getting a new error but finally got past the ORFinder one. I just reinstalled bakta using conda, but in a new environment as suggested. However, I am using Linux.

Maybe you can try using the web version or install the equivalent of WSL for mac ? I used the web version of Bakta yesterday and (gladly !!), the results seem to be the same so far.

**Comment by cuongngh** [comment]
> Hi @cuongngh , I am getting a new error but finally got past the ORFinder one. I just reinstalled bakta using conda, but in a new environment as suggested. However, I am using Linux.
> 
> Maybe you can try using the web version or install the equivalent of WSL for mac ? I used the web version of Bakta yesterday and (gladly !!), the results seem to be the same so far.

Hi @Sarani-NS, yes I tried the web. Thanks.
