### ISSUE TITLE
No pseudogenes being detected

### ISSUE THREAD

**Issue by flashton2003** [oschwengers/bakta#320]
Hi Oliver,

We are interested in pseudogenes in a Salmonella genome. My colleague has run bakta, but no pseudogenes are being detected. This is unexpected based on some other analyses we have carried out, but I haven't been able to identify any specific discrepancies (the other analysis is a random forest, and I haven't unpicked it yet).

Bakta was installed via conda. The bakta output directory can be downloaded from here as a dropbox link.

https://www.dropbox.com/scl/fo/3ml720rn2clv2f68sc2qm/AHrkm3NUddod6KWhQRggpJw?rlkey=m7vl1loes8ij9ppny2zm29ubu&dl=0

Any thoughts?

Thanks,

Phil

**Comment by oschwengers** [comment]
Hi Phil,
based on the logs the `light` db version was used. For the pseudogene detection, however, Bakta requires the `full` db version. Maybe I just add a line to STDOUT to clearly express this behavior.

Best regards!

**Comment by flashton2003** [comment]
Great, thanks Oliver!

**Comment by oschwengers** [comment]
FYI: the upcoming `v1.10.0` will print a short note to STDOUT -> https://github.com/oschwengers/bakta/commit/c8a93e11cae31db58eab3711ca344e3ceaf35eba

Thanks for reaching out/reporting!

**Comment by flashton2003** [comment]
Great, thanks Oliver!
