### ISSUE TITLE
Increase verboisity for invalid --proteins options

### ISSUE THREAD

**Issue by NonAggressiveHail** [oschwengers/bakta#322]
When providing an incorrectly formatted genbank or fasta file with the --proteins option no information is given on why the file in invalid.

I attempted to annotate a genome with [these](https://www.ncbi.nlm.nih.gov/nuccore/AY765263.1) reference proteins, downloaded as GenBank file format. When bakta annotates CDS the error is given "ERROR: User proteins file GenBank format not valid!". Rerunning with --debug option I expected more information on how this file is invalid  so I can repair it, but no further information is given. Ideally, more information should be given on what aspects of the file are invalid so they can be repaired. 

I have also tried converting the Genbank file to a fasta file with prokka's prokka-genbank_to_fasta_db, however using this gave the error "ERROR: User proteins file Fasta format not valid!". Again it would be helpful for this to provide further information on why it is invalid, or for bakta to include a utility with similar functionality which works correctly.

**Comment by NonAggressiveHail** [comment]
Just realised I have been misinterpreting the user protein sequences text. I had thought it was the provided number of user proteins, when in actual fact it appears to be the number of user proteins found in the target sequence. I don't think that there is a bug here anymore, but still think that increased information on what is invalid about a file would be useful.

**Comment by oschwengers** [comment]
Hi @NonAggressiveHail ,
thanks for reaching out and reporting. Indeed, it would be nice to have some more-verbose output on many errors. However, this is far from trivial, or at least very labor intensive to catch all potential cases. But, I'll have a thought on it.

Since there is no actual bug, I'll close this for now.
