### ISSUE TITLE
translation-table code 25

### ISSUE THREAD

**Issue by ndombrowski** [oschwengers/bakta#323]
Thanks for the great tool,

I have a question: at the moment Bakta allows to choose between translation tables 4 and 11 and I was just wondering if it would be possible to implement code 25 for Candidate Division SR1 and Gracilibacteria as well?

Thanks a lot for considering!
Regards,
Nina

**Comment by miguellords** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by oschwengers** [comment]
Hi @ndombrowski , thanks for asking.
Bakta uses Pyrodigal and BioPython for all internal translations. Based on a quick look into docs/codes of both, this should   in principle be no problem. 

Could you provide or point me to a public test genome?

**Comment by ndombrowski** [comment]
Hi @oschwengers, thanks for the quick reply.

There is no type material as far as I know but [Aalborg_AAW-1](https://gtdb.ecogenomic.org/genome?gid=GCA_001007975.1) should do and is also annotated with translation table 25 in [NCBI](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/007/975/GCA_001007975.1_ASM100797v1/).

Thanks a lot for checking!

**Comment by oschwengers** [comment]
Thanks a lot! 

I've added support for translation table `25`. A quick test based on your test genome was successful.

Now, this is active in the `main` branch, and will be publicly available in the upcoming `v1.10.0` - then, Bakta should be ready to conquer Candidate Division SR1 and the _Gracilibacteria_  ;-)

I'll close this. If there are any issues or questions, please, do not hesitate to re-open it.
