### ISSUE TITLE
how to obtain the sequences of crispr and tRNA in bakta output files?

### ISSUE THREAD

**Issue by YoungerRen** [oschwengers/bakta#336]
dears
Thanks a lot for developing such a great software, all processes run smoothly for me. But I have a request about the output file: bakta's output file checks the number of crispers and tRNAs, and I happen to need both output files when I do virus host prediction, and I'm wondering how to get the coding sequences of both in the output file, not just the number.

sincerely
Younger

**Comment by oschwengers** [comment]
Hi @YoungerRen , thanks for reaching out.
As far as I understand you correclty, you need the nucleotide sequences of _tRNA_ and _CRISPR_  features? You find the nucleotide sequences of these (and all other detected features) in the `*.ffn` output file.

I hope this is what you're looking for.
Best regards!

**Comment by oschwengers** [comment]
Hey @YoungerRen , I'm sorry, I just recognized that CRISPR arrays were indeed not included in the `<prefix>.ffn`output files. This is now fixed in fac21b7451bdaa34449bb92883b54897601bb9c4 and will be available soon with the upcoming `v1.10.0` release.

Best regards.
