### ISSUE TITLE
Dockerfile not OCI compliant

### ISSUE THREAD

**Issue by MariusDieckmann** [oschwengers/bakta#34]
**Describe the bug**
When building the docker image with buildah an error message occurs that states that the "SHELL" command is not OCI compliant:
ERRO[0000] SHELL is not supported for OCI image format, [bash -l -c] will be ignored. Must use `docker` format 

Should we change this to be OCI compliant?

**Comment by oschwengers** [comment]
It would definitely be nice to have this OCI compliant but I currently see no easy way how to do this and thus are rather reluctant to take a closer look into this. However, I'm happy to receive PR on this. I'll close this for now, please reopen if this becomes a more severe issue.
