### ISSUE TITLE
Issue with Dockerfile file

### ISSUE THREAD

**Issue by pamelacamejom** [oschwengers/bakta#342]
Hi, I am trying to build a docker using the dockerfile (I need to use the new --skip-filer option), however I have the following issue when I try building this docker:

`bin/micromamba
The following argument was not expected: -p
Run with --help for more information.
The command '/bin/sh -c apk update && apk add wget tar bash     && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub     && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-2.32-r0.apk     && apk add glibc-2.32-r0.apk     && rm glibc-2.32-r0.apk     && wget --no-iri -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba     && touch /root/.bashrc     && ./bin/micromamba shell init -s bash -p /opt/conda      && cp /root/.bashrc /opt/conda/bashrc' returned a non-zero code: 109
`

**Comment by oschwengers** [comment]
Hi @pamelacamejom , thanks for reporting, and sorry, somehow I must have missed this issue. There is a PR (#345 ) fixing this. I'll release a patch v1.10.1 ASAP once the PR is accepted.
