### ISSUE TITLE
Is "Genomeviewer" working in the web version of Bakta?

### ISSUE THREAD

**Issue by ilnamkang** [oschwengers/bakta#348]
Is "Genomeviewer" working in the web version of Bakta?

I submitted two complete bacterial genomes (one monoderm and one diderm) to the Bakta web version.

But, I cannot see anything on the "Genomeviewer" panel of my annotation result links.

Thanks.

**Comment by oschwengers** [comment]
Hi @ilnamkang. Thanks for reaching out. Indeed, we have to adopt the web version to some internal changes of the new `v1.10.1` CLI release. Please stay tuned, we're working on this.

For all web-related issues, may I kindly refer you to this repo: https://github.com/ag-computational-bio/bakta-web-ui

**Comment by ilnamkang** [comment]
Thank you for letting us know what is happening.

Sorry for posting this issue here. If I checked "About" section of the Bacta web homepage more carefully, I would have known about the repository you mentioned.

**Comment by lukasjelonek** [comment]
@ilnamkang I updated the website. It now should support the latest bakta file schema.

**Comment by ilnamkang** [comment]
Thanks for your efforts. It is working perfectly.
