### ISSUE TITLE
ERROR: database file (antifam.h3i) not readable!

### ISSUE THREAD

**Issue by Hedi65** [oschwengers/bakta#357]
Dear developer 

I used Bakta as an apptainer container and manually downloaded the full db from Zenodo. This is my command line  

(base) [user@cn-5 New_Round_Analyses_2024]$ apptainer exec /Tools/bakta\:1.10.3--pyhdfd78af_0 bakta --db ./db ./assemblies/test.fasta --output ./bakta_output --force

I received some warnings, which were already discussed in the forum, but I also received an error due to one of the files in my database. Do you have any idea how I can fix this? 

/usr/local/lib/python3.11/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.11/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/usr/local/lib/python3.11/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.11/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)

ERROR: database file (antifam.h3i) not readable!

Thanks in advance

**Comment by oschwengers** [comment]
Hi @Hedi65 , hmm, sounds a bit odd. Are you sure that all DB files are properly in place? Im wondering why this error occurs at the antifam stage. This would either mean that you have skipped all earler steps in the workflow, or the DB is in place but there is an issue with this file. Could you attach the log file?

**Comment by Hedi65** [comment]
Thanks for your reply 

Just a quick update: I downloaded the DB using the bakta_db download command instead of manually downloading it, and Bakta is running without problems. 

Thanks

**Comment by oschwengers** [comment]
OK, glad that it is running now as expected. So, happy annotating!
