### ISSUE TITLE
Add detection of pseudo genes

### ISSUE THREAD

**Issue by oschwengers** [oschwengers/bakta#4]
First hints for ideas:
- https://github.com/nigyta/dfast_core
- https://github.com/filip-husnik/pseudofinder#how-does-pseudofinder-detect-pseudogene-candidates

**Comment by oschwengers** [comment]
idea for workflow:
1. start from CDS w/o annotations: either no hits at all or still `hypothetical`
2. re-search pseudogene candidates against Bakta DB using the following thresholds:
  - identity >=80%
  - query coverage >=80%
  - subject coverage >=40%
 3. align subject AA sequence against translated CDS region plus `N` bp up-/downstream
 4. look for `frameshifts` or `stop codons`

**Comment by amvarani** [comment]
Hi there,
So, how bakta last version deal with pseudogenes ?

**Comment by oschwengers** [comment]
Hi @amvarani , thanks for reaching out on this. We're actively working on a first pseudogene detection/annotation feature as a default step in the Bakta workflow. We're currently fixing the last little things and look forward to release a new version very soon (i.e. next weeks).

There are different strategies how to detect pseudogenes, the most promising would be to use a closely related genome - however, as this is often not the case in a *de novo* assembly/annotation workflow, we address this without external genome information.
At this point, Bakta will look for gene residues that could not be annotated (hypothetical proteins) b/c hits for these gene residues only result in Diamond hits with less than 80% subject coverage. In a second more relaxed search Bakta looks for decent hits against the database with subject coverages of less than 80%. These references are then blasted against the 6 frame-translated CDS regions of the hypotheticals plus a 300 bp extension in up- and downward direction. If Bakta finds a conserved homology, it tries to detect indels/mutation and start/stop codon events. If this is the case, the hypothetical gene is annotated as a pseudo gene. Later, we'll extent this approach by taking into account spare genomic regions (w/o annotations), using some information to detect & annotate translational exceptions and so on.

I hope this answers your question. Best regards!
