### ISSUE TITLE
Improve annotation of phage-borne genes

### ISSUE THREAD

**Issue by oschwengers** [oschwengers/bakta#43]
Pre-annotation of UniRef90 clusters could be improved using a dedicated phage database like:
- VOGDB: http://vogdb.org/download
- PHROGs: https://phrogs.lmge.uca.fr/READMORE.php

**Comment by camilogarciabotero** [comment]
Hi @oschwengers,

Just wanted to leave here a new resource I found that could be useful for this issue/feature: [Pharokka](https://github.com/gbouras13/pharokka).

Best.
