### ISSUE TITLE
Bakta process exit with error - amrfinder error code 1

### ISSUE THREAD

**Issue by naturepoker** [oschwengers/bakta#49]
Hi, 

I'm trying to test out Bakta on our newly sequenced bacterial genome (1 chromosome, 6 other genomic compartments in one multifasta file), hopefully comparing against existing Prokka+custom database pipeline. However, the process exits with error message once it gets to 'conduct expert systems...' stage under 'predict & annotate CDSs...' I can replicate this issue on both our lab's server and on my personal laptop (both running Ubuntu, 20.04 and 21.04). 

Bakta was installed with conda/bioconda in both of the instances using below command, running on Ubuntu. 

`conda create -n bakta bakta`

The annotation process command was: 

`bakta --db ~/bakta_data/db/ --output test --genus genusname --species speciesname --threads 20 --replicon replicon.tsv our_assembly.fasta`

The process exits with below error message

```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/bakta/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/bakta/lib/python3.9/site-packages/bakta/main.py", line 276, in main
    expert_amr_found = exp_amr.search(genome['features'][bc.FEATURE_CDS], cds_fasta_path)
  File "/home/user/miniconda3/envs/bakta/lib/python3.9/site-packages/bakta/expert/amrfinder.py", line 33, in search
    raise Exception(f'amrfinder error! error code: {proc.returncode}')
Exception: amrfinder error! error code: 1
``` 

Please let me know if you need more info/tests on my end for troubleshooting. 

Thank you!

**Comment by oschwengers** [comment]
Hi @naturepoker , thanks for trying Bakta and filing this issue!

Bakta internally takes advantage of `AMRFinderPlus` which in turn uses its own databases which must be setup once before the first execution. Seems like this is the case here. Please, try
`amrfinder -u`
to update the internal AMRFinderPlus database.

**Comment by naturepoker** [comment]
Your solution worked perfectly

```
amrfinder -u
```
Above command updates the amrfinder database to version 2021-03-01.1 and the rest of the bakta process finished without any issues. 

Thanks again!

**Comment by lauralwd** [comment]
Hi There, just confirming that I hit the same bug yesterday and that the same fix worked for me. Thanks for all the effort you put into bakta and for sharing it pre-publication. I'm running it on several genomes now and I'm curious to see how it compares!

Back on topic: for ease of use, I had the following two ideas: 
 1. Perhaps it's worth time/effort to include `amrfinder --update` in `bakta_db download` by default. At least that seems logical to me as long as bakta will halt on this amrfinder issue. 
 2. Secondly, how about a "pre-flight check" for amrfinder along with other dependencies in `utils.py`. Perhaps one check for `amrfinder` presence, and a second for the version number of the database in `envs/bakta/bin/data/*/version.txt` 
 
Thanks again!

**Comment by oschwengers** [comment]
Thanks @lauralwd for the confirmation and your suggestions - excellent ideas!

1) will be added as soon as possible.
2) is already implemented, just needs some testing.

**Comment by lauralwd** [comment]
Sound like great progress. If you'd appreciate a pull request just let me know. I'm not that fluent in python but I think I can handle this. 

off-topic------------
annotations are looking great to me. At least similar to previous tools I used and trust, but the bakta names for genes are a bit more verbose which makes it easier for me to interpret. My favourite feature is the extra information for hypothetical proteins.

**Comment by oschwengers** [comment]
@lauralwd thanks for the offered help but it's already implemented: https://github.com/oschwengers/bakta/tree/catch-amrfinderplus-db-issue
I'm just running some final tests.

**Comment by oschwengers** [comment]
it's online. I'll release a patch version soon.
