### ISSUE TITLE
output nucleotide sequences for each CDS

### ISSUE THREAD

**Issue by mcroxen** [oschwengers/bakta#57]
Would it be possible to also output the nucleotide sequence for each CDS, similar to what is already output for the translated protein?

**Comment by oschwengers** [comment]
That should not be problem at all, just a little bit of coding work that needs to be done. I put this on the list for a `v1.1` release.

I will also export nucleotide sequences of all other features which have a `locus_tag` and merge all these nucleotide seqs in a single nucleotide feature file, if that would be OK.

**Comment by oschwengers** [comment]
Hi, nucleotide sequences for features with a `locus_tag` are now exported to an `.ffn` file (to follow the Prokko "convention").
I'm planning to release version 1.1.0 in the next weeks and close this for now. If there are any issues now or later, please do not hesitate to re-open this or open a new issue.
