### ISSUE TITLE
Error version tRNAscan-SE with ubuntu 20.04

### ISSUE THREAD

**Issue by Nilad** [oschwengers/bakta#67]
With Ubuntu 20.04, the version in the repo of tRNAscan-SE is `2.0.5-1`

I got this error in the call of `bakta`

`ERROR: Wrong tRNAscan-SE version installed. Please, either install tRNAscan-SE version v2.0.6 or use ['--skip-trna']!`

With Ubuntu 21.04, the version in the repo of tRNAscan-SE is `2.0.7+ds-1`, i dont encounter this error in bakta.

**Comment by oschwengers** [comment]
Hello,
so actually this is not a bug. Bakta takes care of the right version of `tRNAscan-SE`. If the Ubuntu onboard versions are too old (a common issue), please try `Conda` or `Docker` isntead.

**Comment by Nilad** [comment]
Thanks for your reply. 

For my usage, i make my own `Singularity` recipes.

It's just a backfeed in regards to your `README.md` doc/file --> `Tested with Ubuntu 20.04 - some older distributions might provide outdated versions, e.g. trnascan-se in Ubuntu 18.04. In these cases dependencies must be installed manually.`

**Comment by oschwengers** [comment]
Ah, I see. Thanks for pointing this out. I guess we increased the tRNAscan-SE dependency version after the tests. I'll update the readme accordingly soon.
Thanks again!
