### ISSUE TITLE
Improve AMRFinderPlus integration

### ISSUE THREAD

**Issue by oschwengers** [oschwengers/bakta#68]
1. Execute `AMRFinderPlus` with a custom `$TMPDIR` location pointing to Bakta's internal tmp dir.
2. Write `AMRFinderPlus`'s db to a subdir within the Bakta database directory via `amrfinder_update --database <db>/amrfinderplus/ --force_update` and `amrfinder --protein <input> --database <db>/amrfinderplus/latest` as suggested in https://github.com/oschwengers/bakta/discussions/64

**Comment by ChadoNihi** [comment]
Any estimate on when a version of Bakta w/ this fix and the subsequent changes will be released? Thank you.

**Comment by oschwengers** [comment]
I'm currently fiddling around with the last smaller issues. I hope to release `v1.1.0` today or tomorrow.
