### ISSUE TITLE
Add OrthoSearch of reference files

### ISSUE THREAD

**Issue by Tonny-zhou** [oschwengers/bakta#76]
Dear all,
Thank you for this amazing annotation tool for bacterial genomes! I want to known if you can add an option for orthosearch if we have Genbank or Protein FASTA file(s) that we want to annotate genes from as the first priority. 
This option has been supplied in softwares dfast-core as "--references" (https://github.com/nigyta/dfast_core) and prokka as "--proteins".

Thanks and regards,
Tonny_Z

**Comment by oschwengers** [comment]
Hi @Tonny-zhou , thanks a lot for your kind feedback! 
Indeed, I've already thought about this sort of feature and I'll address this in the next minor release (`1.2`). However, that might take a while.

**Comment by oschwengers** [comment]
Hi @Tonny-zhou , I've implemented a `--proteins` option to allow users to provide a trusted set of protein sequences as a single Fasta file.

Sequences therein can be annotated with additional information using 2 formats: short and long as described here: https://github.com/oschwengers/bakta#input-and-output

The homology search is implemented as an alignment using Diamond. I might also implement an accompanying GenBank/EMBL converter somewhen in the future.
Best regards!

**Comment by Tonny-zhou** [comment]
Thank you so much!!!
