### ISSUE TITLE
Question about output interpretation

### ISSUE THREAD

**Issue by franciscozorrilla** [oschwengers/bakta#82]
Hi,

I ran this tool on 9 soil isolate genomes, expecting the output to contain a prediction regarding whether the gene/contig is predicted to be in the large circular chromosome or in a plasmid.  When I search through the .json file for the `plasmid` keyword, only get information regarding products:

```
$ while read file;do echo $file && less $file|grep -i plasmid;done< <(ls|grep json )
metagem_lane821s003035.json
                "product": "Oligoendopeptidase F, plasmid"
metagem_lane821s003036.json
metagem_lane821s003037.json
                "product": "Oligoendopeptidase F, plasmid"
                "product": "RepB family plasmid replication initiator protein",
metagem_lane821s003038.json
                "product": "Oligoendopeptidase F, plasmid"
            "product": "Plasmid partitioning protein ParB",
                "product": "Plasmid partitioning protein ParB",
            "product": "Plasmid stability protein",
                "product": "Plasmid stability protein",
metagem_lane821s003040.json
            "product": "Plasmid partitioning protein ParB",
                "product": "Plasmid partitioning protein ParB",
                "product": "Oligoendopeptidase F, plasmid"
metagem_lane821s003041.json
            "product": "Plasmid pRiA4b ORF-3-like protein",
                "product": "Plasmid pRiA4b ORF-3-like protein",
metagem_lane821s003042.json
                "product": "Plasmid partitioning protein ParB",
metagem_lane821s003043.json
            "product": "Plasmid pRiA4b ORF-3 family protein",
                "product": "plasmid pRiA4b ORF-3 family protein",
                "product": "Plasmid pRiA4b ORF-3 family protein"
metagem_lane821s003044.json
                "product": "Oligoendopeptidase F, plasmid"
            "product": "Plasmid partitioning protein RepA",
                "product": "Plasmid partitioning protein RepA",
            "product": "Plasmid partitioning protein RepB",
                "product": "plasmid partitioning protein RepB",
                "product": "Plasmid partitioning protein RepB"
            "product": "Plasmid pRiA4b ORF-3 family protein",
                "product": "Plasmid pRiA4b ORF-3 family protein"
```

Is this tool appropriate for identifying plasmids in my isolate genome assemblies?

Thanks and best wishes,
Francisco

**Comment by oschwengers** [comment]
Hi @franciscozorrilla ,
bakta is a tool to "merely" annotate a bacterial genome. Of course you can search for plasmid related genes via their functional descriptions, _i.e._ products. However, there are many potential pitfalls here and I'd urgently recommend not to do this.

To detect plasmids within bacterial draft genomes I may refer you to https://github.com/oschwengers/platon which was especially developed to solve this particular issue. Platon will print potential plasmid-born contigs within your draft assemblies along with information regarding circularity, incompatibility factors, replicon/mobilization/conjugation genes as well as plasmid hits. This is based on the detection of plasmid related marker protein genes and so-called replicon distribution scores(RDS). Of course, there are many other tools to solve this task.

I hope I could clarify a little bit. As this is not directly related to bakta, I'll close this for now. Please, do not hesitate to keep asking and re-opening this just in case.

Best regards,
Oliver

**Comment by franciscozorrilla** [comment]
Hi @oschwengers,

Thank you very much for the quick and informative response! I will keep using bakta for genome annotation but will try out platon for plasmid identification, it looks like its exactly the tool I need. I will open an issue in that repo if I run into any problems or have questions regarding the interpretation of results.

Thanks again and best wishes,
Francisco
