### ISSUE TITLE
The online service lacks error message

### ISSUE THREAD

**Issue by shenwei356** [oschwengers/bakta#84]
Hi Oliver,  I'm using the online service (https://bakta.computational.bio/). After submission, the status changed from INIT to ERROR, but no further information are shown. The job ID is d185987b-8d57-43b2-9813-63ea2d52c512, can you help to improve the log?

I'll try the local version.

**Comment by oschwengers** [comment]
Hi @shenwei356  and thanks a lot for the report. We're currently improving on the internal logging and will come back on this soon.
Meanwhile, have you tried the CLI version? Are there any issues with that, too?

**Comment by shenwei356** [comment]
Thanks for your reply.

> have you tried the CLI version?

Not yet, I submitted to NCBI Genbank to annotate using PGAP 😂 Please give me some time.

**Comment by shenwei356** [comment]
The CLI version works smoothly with the same assembly sequence.

**Comment by oschwengers** [comment]
Thanks - that's good to know and helps to locate the issue.

**Comment by oschwengers** [comment]
@shenwei356 we've added a few more checks and tests both to the web and CLI versions, as well as more detailed logging.
Hence, may I kindly ask you to try the web version again using exactly the same genome and parameters?

**Comment by shenwei356** [comment]
It works (id `679c1fba-c826-473d-9db1-745e1e952c57`).

I tried my best with parameters, but now `Locus tag prefix` does not allow an underline, so this may be the only difference (`NMCQ_` -> `NMCQ`)

**Comment by shenwei356** [comment]
Nice work, Thank you! I've introduced the web service to my colleagues and friends.

**Comment by shenwei356** [comment]
Another issue, the input checking did not recognize `\r` in sequences uploaded by Windows users with `\r\n` as newline symbols.

Those who do not know `\r` would feel confused and frustrated in one second and give up trying :joy:

**Comment by oschwengers** [comment]
Oh, thanks for the heads up!
I guess we never used/tested input data from a Windows system. We'll fix that.

**Comment by oschwengers** [comment]
We tested both the web and CLI version with Windows formatted Fasta input files. Unfortunately, we cannot reproduce this error. Could you please elaborate a little bit more on that and provide some more details? What have you uploaded how (file or via the sequence input field) and what exactly happend thereafter?
Best regards!

**Comment by shenwei356** [comment]
It's weird, I can't reproduce it either.  My friend deleted all `\r` and still failed. But I successfully submitted with the same genome :(

<img width="761" alt="7b4ae1a77bf188dc9a34dee35fc1c64" src="https://user-images.githubusercontent.com/2655946/143671259-1a46a544-f375-4851-9a2e-24644731d3d6.png">

**Comment by oschwengers** [comment]
That's weird indeed. How does the error occur: via pasting the sequence into the text box or via uploading it as a fasta file?
Could you provide us the sequence or the fasta file so that we can try to reproduce the error?

**Comment by shenwei356** [comment]
I ask again and confirm that my friend can successfully submit jobs. 

He just told me that he used a non-modern browser that day -_-! The embedded browser of WeChat...

So forget this issue. Thanks, Oliver!

**Comment by oschwengers** [comment]
Ah... OK.
Thanks for the note; I guess we won't dare to provide support for this ;-) 

Best regards!
