### ISSUE TITLE
Can't use bakta_db

### ISSUE THREAD

**Issue by andreaniml** [oschwengers/bakta#85]
Hi!
I'm getting an error when I try to list or download a database , bakta_db list and bakta_db download both give this same error:

```
Required database schema version: 3

Traceback (most recent call last):
  File "/home/malu/anaconda3/envs/bakta/bin/bakta_db", line 10, in <module>
    sys.exit(main())
  File "/home/malu/anaconda3/envs/bakta/lib/python3.10/site-packages/bakta/db.py", line 171, in main
    versions = fetch_db_versions()
  File "/home/malu/anaconda3/envs/bakta/lib/python3.10/site-packages/bakta/db.py", line 103, in fetch_db_versions
    with requests.get(bc.DB_VERSIONS_URL) as resp:
AttributeError: module 'bakta.constants' has no attribute 'DB_VERSIONS_URL'
```
I've installed using conda
I don't have a clue on what could be causing it (could be a firewall problem? I've been having problems with zenodo, however it feels like it crashes before even trying to download)

Thanks for any help!

**Comment by oschwengers** [comment]
Hi @andreaniml ! Thanks for reporting, indeed a required constant was accidentally removed in a recent commit. It's fixed and I'll release a patch version to propagate the fix, today.

**Comment by oschwengers** [comment]
The hotfixing patch release is public: https://github.com/oschwengers/bakta/releases/tag/v1.2.4
You can update Bakta to this latest version via `conda install bakta=1.2.4`

Thanks again for reporting! I close this for now. Please, do not hesitate to re-open it just in case.
