### ISSUE TITLE
Bakta having problems handling Ns - invalid DNA characters

### ISSUE THREAD

**Issue by RotimiDada** [oschwengers/bakta#87]
Thank you @oschwengers and the team for introducing this tool. Your adherence to the FAIR principles is a huge contribution.

I have contigs from reference-based alignment and some genes of interest in the contigs. I need to annotate the contigs to get some information for downstream analyses. My problem is with a call from bakta that **_"fasta sequence contains invalid DNA characters"._** My guess is that Ns are called invalid DNA characters by bakta. 

Here is the content of the log file showing the error message: 

_15:30:05.858 - ERROR - FASTA - import: Fasta sequence contains invalid DNA characters! id=%s
15:30:05.859 - ERROR - MAIN - wrong genome file format!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bakta/main.py", line 124, in main
    contigs = fasta.import_contigs(cfg.genome_path)
  File "/usr/local/lib/python3.9/site-packages/bakta/io/fasta.py", line 26, in import_contigs
    raise ValueError(f'Fasta sequence contains invalid DNA characters! id={record.id}')
ValueError: Fasta sequence contains invalid DNA characters! id=INOLLH026C
15:30:05.862 - INFO - MAIN - removed tmp dir: /tmp/tmpzubdk5dw_

Thank you for your help 
----Rotimi

**Comment by oschwengers** [comment]
Hi @RotimiDada , thanks for reporting this. Since you mentioned aligned contigs:

We strive to have Bakta accepting allmost all valid IUPAC nucleotide characters of a DNA Fasta file. Currently, these are: `ATGC`, `N` and the ambiguity codes `MRWSYKVHDBN`.

Due to the fact that is not supported by 3rd party tools involved in the workflow, the only character that is excluded on purpose is `-`. Could you check if that is included in contig `INOLLH026C`?

**Comment by RotimiDada** [comment]
Thank you Oliver for  a super fast response. I have checked the contigs and can't seem to find "-" character in them. 

[INOLLH026C.txt](https://github.com/oschwengers/bakta/files/7655990/INOLLH026C.txt)

I am attaching the fasta file for you to see if you could also reproduce this error.

By the way, Prokka annotates these files without encountering errors, but I need the annotation to conform to the nomenclature of the databases that I used for calling my genes of interest (e.g. Virulencefinder) - FAIR.......

**Comment by oschwengers** [comment]
That sounds interesting. Unfortunately, the file you've provided is not the Fasta file. Could you attach the input Fasta file you've used for the annotation so I can take a look at that?

**Comment by RotimiDada** [comment]
Thank you once again Oliver. I am sorry. I don't know I erroneously sent you an annotation file. Please find attached the fasta file. 

---Kind regards,
Rotimi
[agg3CD_INOLLH026C.fa.zip](https://github.com/oschwengers/bakta/files/7660327/agg3CD_INOLLH026C.fa.zip)

**Comment by oschwengers** [comment]
Dear Rotimi,
I found a total of 9 dashed (`-`) in your Fasta file, for instance in line 277 character 39:
`AATATCCTGAAGAGTTTTGCTCCTGGTAATTAATTATT-CTGAATTATTACCTTACATGG`

These are not compatible with 3rd party tools, _e.g._ Infernal that are used in the workflow. When I remove all these dashes (Prokka does that automatically) Bakta successfully annotates this amended Fasta file:
[bakta.zip](https://github.com/oschwengers/bakta/files/7660871/bakta.zip)

Thank you very much for reporting and bringing up this issue. As this might affect other users as well, I think I will add an automated removal of dashes soon.

**Comment by RotimiDada** [comment]
Dear Oliver, 

Many thanks for your help. I can also confirm that after removing the dashes, bakta ran successfully. I am sorry for having to make you spot the dashes yourself, after I failed to detect dashes in my first attempt. By the way, thank you for planning to automate dash removal.

Warm regards,
---Rotimi

**Comment by oschwengers** [comment]
You're welcome! For the sake of documentation, a soon-to-come commit will address this issue. Therefore, I'll keep this still open for a while.
Best regards!

**Comment by RotimiDada** [comment]
My thoughts exactly. Cheers!
