### ISSUE TITLE
Summary information file

### ISSUE THREAD

**Issue by hkaspersen** [oschwengers/bakta#88]
**Is your feature request related to an existing issue or bug?**
Could not find any previous issues for this.

**Is your new feature related to a general problem?**
Prokka has an output file that contains summarised information regarding the annotations in the current run, it looks like this:
```
organism: Genus species strain 
contigs: 60
bases: 1963966
CDS: 1905
gene: 1930
rRNA: 3
repeat_region: 1
tRNA: 21
tmRNA: 1
```
It would be awesome if something similar could be added to bakta, as it is very useful. Thanks for considering!

**Comment by oschwengers** [comment]
Sure, that should not be a problem. I've put this on the list for an upcoming minor version [v1.3](https://github.com/oschwengers/bakta/milestone/5).

**Comment by oschwengers** [comment]
I've added a new `<prefix>.txt` file providing the following information:

```
Sequence(s):
Length: 3,306
Contigs/replicons: 1
GC: 43.4
N50: 3,306
N ratio: 0.0
coding density: 65.2

Annotation:
tRNAs: 0
tmRNAs: 0
rRNAs: 0
ncRNAs: 0
ncRNA regions: 0
CRISPR arrays: 0
CDSs: 3, hypotheticals: 3
sORFs: 0
gaps: 0
oriCs: 0
oriVs: 0
oriTs: 0
```
Just a small test plasmid, so not much in here but should work as an example. You can use the current main branch until the next release. I'll close this for now but do not hesitate to re-open it just in case.
Best regards!
