### ISSUE TITLE
Could it be possibile for providing gbk format file for the param --proteins ?

### ISSUE THREAD

**Issue by Tonny-zhou** [oschwengers/bakta#89]
**Is your feature request related to an existing issue or bug?**
Briefly reference any existing issues this is related to.

**Is your new feature related to a general problem?**
Please provide us with a concise description of what the problem is:
- what happened which was *not* expected
- what did *not* happen which was expected
- what would you like to happen or see in the output
- 
Could it be possibile for providing gbk format file for the param --proteins ? Because for many new hands, using the gbk files downloaded from the NCBI database  would be easier than using the fasta files formatted  by themselves.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context or information about your feature request here.

**Comment by oschwengers** [comment]
Hi @Tonny-zhou,
I added support for user proteins provided in GenBank format. The following information are extracted from `CDS` features:
- gene
- product
- EC_number
- db_xref

I guess this will be public with an upcoming 1.3 release but you could install the latest version from `main` meanwhile. Please, let me know if this fits your needs.

**Comment by oschwengers** [comment]
I'll close this for now. Please, don't hesitate to re-open it in any case.
