### ISSUE TITLE
Where are the EC numbers?

### ISSUE THREAD

**Issue by pavlohrab** [oschwengers/bakta#99]
I could not find the EC numbers in the output of the Bakta, but the documentation says they should be there.

Using:
- CLI interface
- Bakta v 1.3.3
- Database v 3.1

Bakta was installed via bioconda, database was downloaded  via `bakta_db download -o <database-path>`.

For comparison I annotated the same file the prokka and the EC numbers were there

**Comment by oschwengers** [comment]
Hi,
you find them in the various output formats under the database cross-reference (`/db_xref="EC:2.7.1.39`) like `<prefix>.tsv`, `<prefix>.gff3`, `<prefix>.json` and the INSDC formats GenBank and EMBL.
Of course, only if such an annotation is available for a certain protein.

**Comment by pavlohrab** [comment]
Yes, I understand. But here you can see a result of a search via `grep -F -f <EC.numbers.file> <annotation.tsv>` for prokka:
![image](https://user-images.githubusercontent.com/38843017/158783607-b08d5d52-bbf9-4c92-aee5-61f283987859.png)

But no results are returning for bakta for the same contigs file I am trying to annotate. Also there is no results is you search "EC:"  in the `.tsv` or `.gff3` files.

I made a run with default settings (only changed `--threads` parameter). So am I missing smth?

**Comment by oschwengers** [comment]
Default settings are just fine. Without further information on the species (or the actual genome) I can only speculate that in this case Bakta doesn't find any annotations providing EC numbers. May I ask which genus db or proteins file you use for the Prokka annotation? If you have a decent annotation you could provide them to Bakta via `--proteins` either in GenBank or Fasta format.

However, currently only ~335k of 91M reference proteins in Bakta's db are actually annotated with EC numbers. That's something we have on our list for upcoming improvements.

**Comment by oschwengers** [comment]
Hi @pavlohrab ,
FYI, I just released version [v1.5.0](https://github.com/oschwengers/bakta/releases/tag/v1.5.0) introducing the pre-annotation of `PSC`s with KEGG's Kofams which adds ~9 mio additional `E.C.` numbers. Therefore, it might be interesting to to give Bakta a second try ;-)
Cheers!

**Comment by oschwengers** [comment]
Hi,
do you use the latest software and database versions (Bakta `v1.8.2` and db `v5.0`)?

**Comment by jsgounot** [comment]
Yes, full DB description below:

```
{
  "date": "2023-02-20",
  "major": 5,
  "minor": 0,
  "type": "full",
  "doi": "10.5281/zenodo.7669534",
  "software-min": {
      "major": 1,
      "minor": 7
  },
  "dependencies": [
    {
      "name": "AMRFinderPlus",
      "release": "2022-12-19.1"
    },
    {
      "name": "COG",
      "release": "2020"
    },
    {
      "name": "DoriC",
      "release": "12"
    },
    {
      "name": "ISFinder",
      "release": "2019-09-25"
    },
    {
      "name": "Mob-suite",
      "release": "2.0"
    },
    {
      "name": "Pfam",
      "release": "35"
    },
    {
      "name": "RefSeq",
      "release": "r216"
    },
    {
      "name": "Rfam",
      "release": "14.9"
    },
    {
      "name": "UniProtKB/Swiss-Prot",
      "release": "2022_05"
    },
    {
      "name": "VFDB",
      "release": "2023-02-10"
    }
  ]
}
```

**Comment by oschwengers** [comment]
Have you provided any additional info to Prokka like for instance reference proteins? If this is the case, you can also provide them to Bakta via `--proteins`. If not, then it seems like in this case or for this species, Prokka indeed provides more EC numbers.
